(* jpl_bodies_diff.ml — the OCaml half of the rendered-bodies differential,
   5-B.3b-ii-a.  GENERATED by verify/c/jpl_lower.ml from the same RENDER rows that
   wrote sh_run_jpl_bodies.c — DO NOT EDIT, and do not add a call to it by hand.
   Compiled against the vendored extraction (src/kernel/sh_run_c.ml{,i}), the SAME
   artifact the census read, and printing the SAME 136450 lines (5 fields) as the C
   driver jpl_bodies_diff.c, over 0 … mAX_FUEL.  `cmp` of the two transcripts is
   the rung that turns "the renderer wrote C" into "the C computes what the
   extracted kernel computes", over every bounded input. *)

let () =
  let fuel = Sh_run_c.mAX_FUEL in
  for i = 0 to fuel do
    Printf.printf "%d %d %d %d %d\n" i (Sh_run_c.bstat i) (if (Sh_run_c.is_digit i) then 1 else 0) (if (Sh_run_c.is_alpha i) then 1 else 0) (if (Sh_run_c.is_name i) then 1 else 0)
  done
