/* jpl_bodies_diff.c — the C half of the rendered-bodies differential, 5-B.3b-ii-a.
   GENERATED by verify/c/jpl_lower.ml from the same RENDER rows that wrote
   sh_run_jpl_bodies.c — DO NOT EDIT, and do not add a function to it by hand.
   Link with sh_run_jpl_bodies.c; print the 136450 lines (5 fields: the index, then one
   per rendered body in artifact order) the OCaml driver jpl_bodies_diff.ml prints,
   over 0 … JPL_MAX_FUEL — the cap the artifact carries, not a range chosen here.
   A HOST driver: <stdio.h> and printf are this file's business, not the shipped
   kernel's, so JPL.6's lint does not audit it. */

#include <stdio.h>
#include "sh_run_jpl.h"

int main(void)
{
  jpl_nat i;
  for (i = 0u; i <= JPL_MAX_FUEL; i = i + 1u) {
    printf("%u %u %u %u %u\n", i, jpl_bstat(i), jpl_is_digit(i), jpl_is_alpha(i), jpl_is_name(i));
  }
  return 0;
}
