/* sh_run_jpl_bodies.c — the function BODIES the lowering census could render,
   JPL.5-B.3b-ii-a.
   GENERATED by verify/c/jpl_lower.ml from the vendored extraction
   (src/kernel/sh_run_c.ml{,i}) over roots mrun_c,step_c — DO NOT EDIT.
   Every definition here ANSWERS a prototype in sh_run_jpl.h, so it is valid only with
   that header, and the gate compiles the two together:
     #include "sh_run_jpl.h"
   A body is here because JPL.md §6.4's render trial accepted it: no pool, no allocator,
   no function value.  Nothing here allocates, so nothing here measures the extent that
   §6.2's headroom factor still owes.  The bodies that were refused, and the construct or
   schema that refused each, are in lowering.txt — the count in this file is not the
   census's opinion of itself, it is the same measurement with C attached. */

#include "sh_run_jpl.h"

/* bstat : nat -> nat
   schema straight-line, verdict RENDER
   cites no data constant, calls no binding */
jpl_nat jpl_bstat(jpl_nat n)
{
  return ((n == 0u) ? 1u : 0u);
}

/* is_digit : nat -> bool
   schema straight-line, verdict RENDER
   cites JPL_C_B_0; calls nothing */
jpl_bool jpl_is_digit(jpl_nat b)
{
  return (jpl_bool) ((JPL_C_B_0 <= b) && (b <= 57u));
}

/* is_alpha : nat -> bool
   schema straight-line, verdict RENDER
   cites no data constant, calls no binding */
jpl_bool jpl_is_alpha(jpl_nat b)
{
  return (jpl_bool) (((65u <= b) && (b <= 90u)) || ((97u <= b) && (b <= 122u)));
}

/* is_name : nat -> bool
   schema straight-line, verdict RENDER
   cites JPL_C_B_USCORE; calls is_alpha, is_digit */
jpl_bool jpl_is_name(jpl_nat b)
{
  return (jpl_bool) ((jpl_is_alpha(b) || jpl_is_digit(b)) || (b == JPL_C_B_USCORE));
}

/* rendered bodies: 4 of 47 closure members; the other verdicts are measured in
   lowering.txt and owned by JPL.md §6.3 (§6.4's table says which) */
