/* GENERATED by verify/c/jpl_emit.ml from
   src/kernel/sh_run_c.ml
   src/kernel/sh_run_c.mli
   DO NOT EDIT — the gate re-runs the emitter and byte-compares this file.
   sh_run_jpl_pools.c — the pool DEFINITIONS and the JPL.md §6.6 runtime: the
   only C in this tree that owns a mutable static, and the reason a handle in
   sh_run_jpl.h points at something rather than at a comment.  No number below
   is typed: every dimension is the header's own JPL_POOL_* macro. */

#include "sh_run_jpl.h"

/* ── word: JPL_POOL_WORD cells of jpl_text, handled as jpl_wref ── */
jpl_text jpl_word_pool[JPL_POOL_WORD];
jpl_ref jpl_word_next = 1u;   /* index 0 is JPL_NIL and stays reserved (§6.6) */
jpl_ref jpl_word_peak = 0u;
jpl_ref jpl_word_taken = 0u;
jpl_ref jpl_word_refused = 0u;

jpl_wref jpl_word_alloc(void) {
  jpl_wref h = JPL_NIL;
  if (jpl_word_next < JPL_POOL_WORD) {
    h = jpl_word_next;
    jpl_word_next = jpl_word_next + 1u;
    if (jpl_word_peak < h) {
      jpl_word_peak = h;
    }
    if (jpl_word_taken < JPL_REF_TOP) {
      jpl_word_taken = jpl_word_taken + 1u;
    }
  } else {
    if (jpl_word_refused < JPL_REF_TOP) {
      jpl_word_refused = jpl_word_refused + 1u;
    }
  }
  return h;
}

jpl_ref jpl_word_reset(void) {
  /* next >= 1u by construction, so this subtraction cannot wrap. */
  jpl_ref returned = jpl_word_next - 1u;
  jpl_word_next = 1u;
  return returned;
}

jpl_bool jpl_word_is_live(jpl_ref h) {
  jpl_bool r = JPL_FALSE;
  if ((h != JPL_NIL) && (h < jpl_word_next)) {
    r = JPL_TRUE;
  }
  return r;
}

/* ── pair_text_text_list: JPL_POOL_PAIR_TEXT_TEXT_LIST cells of jpl_pair_text_text_list_cell, handled as jpl_pair_text_text_list ── */
jpl_pair_text_text_list_cell jpl_pair_text_text_list_pool[JPL_POOL_PAIR_TEXT_TEXT_LIST];
jpl_ref jpl_pair_text_text_list_next = 1u;   /* index 0 is JPL_NIL and stays reserved (§6.6) */
jpl_ref jpl_pair_text_text_list_peak = 0u;
jpl_ref jpl_pair_text_text_list_taken = 0u;
jpl_ref jpl_pair_text_text_list_refused = 0u;

jpl_pair_text_text_list jpl_pair_text_text_list_alloc(void) {
  jpl_pair_text_text_list h = JPL_NIL;
  if (jpl_pair_text_text_list_next < JPL_POOL_PAIR_TEXT_TEXT_LIST) {
    h = jpl_pair_text_text_list_next;
    jpl_pair_text_text_list_next = jpl_pair_text_text_list_next + 1u;
    if (jpl_pair_text_text_list_peak < h) {
      jpl_pair_text_text_list_peak = h;
    }
    if (jpl_pair_text_text_list_taken < JPL_REF_TOP) {
      jpl_pair_text_text_list_taken = jpl_pair_text_text_list_taken + 1u;
    }
  } else {
    if (jpl_pair_text_text_list_refused < JPL_REF_TOP) {
      jpl_pair_text_text_list_refused = jpl_pair_text_text_list_refused + 1u;
    }
  }
  return h;
}

jpl_ref jpl_pair_text_text_list_reset(void) {
  /* next >= 1u by construction, so this subtraction cannot wrap. */
  jpl_ref returned = jpl_pair_text_text_list_next - 1u;
  jpl_pair_text_text_list_next = 1u;
  return returned;
}

jpl_bool jpl_pair_text_text_list_is_live(jpl_ref h) {
  jpl_bool r = JPL_FALSE;
  if ((h != JPL_NIL) && (h < jpl_pair_text_text_list_next)) {
    r = JPL_TRUE;
  }
  return r;
}

/* ── cmd: JPL_POOL_CMD cells of jpl_cmd_node, handled as jpl_cmd ── */
jpl_cmd_node jpl_cmd_pool[JPL_POOL_CMD];
jpl_ref jpl_cmd_next = 1u;   /* index 0 is JPL_NIL and stays reserved (§6.6) */
jpl_ref jpl_cmd_peak = 0u;
jpl_ref jpl_cmd_taken = 0u;
jpl_ref jpl_cmd_refused = 0u;

jpl_cmd jpl_cmd_alloc(void) {
  jpl_cmd h = JPL_NIL;
  if (jpl_cmd_next < JPL_POOL_CMD) {
    h = jpl_cmd_next;
    jpl_cmd_next = jpl_cmd_next + 1u;
    if (jpl_cmd_peak < h) {
      jpl_cmd_peak = h;
    }
    if (jpl_cmd_taken < JPL_REF_TOP) {
      jpl_cmd_taken = jpl_cmd_taken + 1u;
    }
  } else {
    if (jpl_cmd_refused < JPL_REF_TOP) {
      jpl_cmd_refused = jpl_cmd_refused + 1u;
    }
  }
  return h;
}

jpl_ref jpl_cmd_reset(void) {
  /* next >= 1u by construction, so this subtraction cannot wrap. */
  jpl_ref returned = jpl_cmd_next - 1u;
  jpl_cmd_next = 1u;
  return returned;
}

jpl_bool jpl_cmd_is_live(jpl_ref h) {
  jpl_bool r = JPL_FALSE;
  if ((h != JPL_NIL) && (h < jpl_cmd_next)) {
    r = JPL_TRUE;
  }
  return r;
}

/* ── text_list: JPL_POOL_TEXT_LIST cells of jpl_text_list_cell, handled as jpl_text_list ── */
jpl_text_list_cell jpl_text_list_pool[JPL_POOL_TEXT_LIST];
jpl_ref jpl_text_list_next = 1u;   /* index 0 is JPL_NIL and stays reserved (§6.6) */
jpl_ref jpl_text_list_peak = 0u;
jpl_ref jpl_text_list_taken = 0u;
jpl_ref jpl_text_list_refused = 0u;

jpl_text_list jpl_text_list_alloc(void) {
  jpl_text_list h = JPL_NIL;
  if (jpl_text_list_next < JPL_POOL_TEXT_LIST) {
    h = jpl_text_list_next;
    jpl_text_list_next = jpl_text_list_next + 1u;
    if (jpl_text_list_peak < h) {
      jpl_text_list_peak = h;
    }
    if (jpl_text_list_taken < JPL_REF_TOP) {
      jpl_text_list_taken = jpl_text_list_taken + 1u;
    }
  } else {
    if (jpl_text_list_refused < JPL_REF_TOP) {
      jpl_text_list_refused = jpl_text_list_refused + 1u;
    }
  }
  return h;
}

jpl_ref jpl_text_list_reset(void) {
  /* next >= 1u by construction, so this subtraction cannot wrap. */
  jpl_ref returned = jpl_text_list_next - 1u;
  jpl_text_list_next = 1u;
  return returned;
}

jpl_bool jpl_text_list_is_live(jpl_ref h) {
  jpl_bool r = JPL_FALSE;
  if ((h != JPL_NIL) && (h < jpl_text_list_next)) {
    r = JPL_TRUE;
  }
  return r;
}

/* ── cmd_list: JPL_POOL_CMD_LIST cells of jpl_cmd_list_cell, handled as jpl_cmd_list ── */
jpl_cmd_list_cell jpl_cmd_list_pool[JPL_POOL_CMD_LIST];
jpl_ref jpl_cmd_list_next = 1u;   /* index 0 is JPL_NIL and stays reserved (§6.6) */
jpl_ref jpl_cmd_list_peak = 0u;
jpl_ref jpl_cmd_list_taken = 0u;
jpl_ref jpl_cmd_list_refused = 0u;

jpl_cmd_list jpl_cmd_list_alloc(void) {
  jpl_cmd_list h = JPL_NIL;
  if (jpl_cmd_list_next < JPL_POOL_CMD_LIST) {
    h = jpl_cmd_list_next;
    jpl_cmd_list_next = jpl_cmd_list_next + 1u;
    if (jpl_cmd_list_peak < h) {
      jpl_cmd_list_peak = h;
    }
    if (jpl_cmd_list_taken < JPL_REF_TOP) {
      jpl_cmd_list_taken = jpl_cmd_list_taken + 1u;
    }
  } else {
    if (jpl_cmd_list_refused < JPL_REF_TOP) {
      jpl_cmd_list_refused = jpl_cmd_list_refused + 1u;
    }
  }
  return h;
}

jpl_ref jpl_cmd_list_reset(void) {
  /* next >= 1u by construction, so this subtraction cannot wrap. */
  jpl_ref returned = jpl_cmd_list_next - 1u;
  jpl_cmd_list_next = 1u;
  return returned;
}

jpl_bool jpl_cmd_list_is_live(jpl_ref h) {
  jpl_bool r = JPL_FALSE;
  if ((h != JPL_NIL) && (h < jpl_cmd_list_next)) {
    r = JPL_TRUE;
  }
  return r;
}

/* ── pair_text_list_cmd_list_list: JPL_POOL_PAIR_TEXT_LIST_CMD_LIST_LIST cells of jpl_pair_text_list_cmd_list_list_cell, handled as jpl_pair_text_list_cmd_list_list ── */
jpl_pair_text_list_cmd_list_list_cell jpl_pair_text_list_cmd_list_list_pool[JPL_POOL_PAIR_TEXT_LIST_CMD_LIST_LIST];
jpl_ref jpl_pair_text_list_cmd_list_list_next = 1u;   /* index 0 is JPL_NIL and stays reserved (§6.6) */
jpl_ref jpl_pair_text_list_cmd_list_list_peak = 0u;
jpl_ref jpl_pair_text_list_cmd_list_list_taken = 0u;
jpl_ref jpl_pair_text_list_cmd_list_list_refused = 0u;

jpl_pair_text_list_cmd_list_list jpl_pair_text_list_cmd_list_list_alloc(void) {
  jpl_pair_text_list_cmd_list_list h = JPL_NIL;
  if (jpl_pair_text_list_cmd_list_list_next < JPL_POOL_PAIR_TEXT_LIST_CMD_LIST_LIST) {
    h = jpl_pair_text_list_cmd_list_list_next;
    jpl_pair_text_list_cmd_list_list_next = jpl_pair_text_list_cmd_list_list_next + 1u;
    if (jpl_pair_text_list_cmd_list_list_peak < h) {
      jpl_pair_text_list_cmd_list_list_peak = h;
    }
    if (jpl_pair_text_list_cmd_list_list_taken < JPL_REF_TOP) {
      jpl_pair_text_list_cmd_list_list_taken = jpl_pair_text_list_cmd_list_list_taken + 1u;
    }
  } else {
    if (jpl_pair_text_list_cmd_list_list_refused < JPL_REF_TOP) {
      jpl_pair_text_list_cmd_list_list_refused = jpl_pair_text_list_cmd_list_list_refused + 1u;
    }
  }
  return h;
}

jpl_ref jpl_pair_text_list_cmd_list_list_reset(void) {
  /* next >= 1u by construction, so this subtraction cannot wrap. */
  jpl_ref returned = jpl_pair_text_list_cmd_list_list_next - 1u;
  jpl_pair_text_list_cmd_list_list_next = 1u;
  return returned;
}

jpl_bool jpl_pair_text_list_cmd_list_list_is_live(jpl_ref h) {
  jpl_bool r = JPL_FALSE;
  if ((h != JPL_NIL) && (h < jpl_pair_text_list_cmd_list_list_next)) {
    r = JPL_TRUE;
  }
  return r;
}

/* ── frame: JPL_POOL_FRAME cells of jpl_frame_node, handled as jpl_frame ── */
jpl_frame_node jpl_frame_pool[JPL_POOL_FRAME];
jpl_ref jpl_frame_next = 1u;   /* index 0 is JPL_NIL and stays reserved (§6.6) */
jpl_ref jpl_frame_peak = 0u;
jpl_ref jpl_frame_taken = 0u;
jpl_ref jpl_frame_refused = 0u;

jpl_frame jpl_frame_alloc(void) {
  jpl_frame h = JPL_NIL;
  if (jpl_frame_next < JPL_POOL_FRAME) {
    h = jpl_frame_next;
    jpl_frame_next = jpl_frame_next + 1u;
    if (jpl_frame_peak < h) {
      jpl_frame_peak = h;
    }
    if (jpl_frame_taken < JPL_REF_TOP) {
      jpl_frame_taken = jpl_frame_taken + 1u;
    }
  } else {
    if (jpl_frame_refused < JPL_REF_TOP) {
      jpl_frame_refused = jpl_frame_refused + 1u;
    }
  }
  return h;
}

jpl_ref jpl_frame_reset(void) {
  /* next >= 1u by construction, so this subtraction cannot wrap. */
  jpl_ref returned = jpl_frame_next - 1u;
  jpl_frame_next = 1u;
  return returned;
}

jpl_bool jpl_frame_is_live(jpl_ref h) {
  jpl_bool r = JPL_FALSE;
  if ((h != JPL_NIL) && (h < jpl_frame_next)) {
    r = JPL_TRUE;
  }
  return r;
}

/* ── frame_list: JPL_POOL_FRAME_LIST cells of jpl_frame_list_cell, handled as jpl_frame_list ── */
jpl_frame_list_cell jpl_frame_list_pool[JPL_POOL_FRAME_LIST];
jpl_ref jpl_frame_list_next = 1u;   /* index 0 is JPL_NIL and stays reserved (§6.6) */
jpl_ref jpl_frame_list_peak = 0u;
jpl_ref jpl_frame_list_taken = 0u;
jpl_ref jpl_frame_list_refused = 0u;

jpl_frame_list jpl_frame_list_alloc(void) {
  jpl_frame_list h = JPL_NIL;
  if (jpl_frame_list_next < JPL_POOL_FRAME_LIST) {
    h = jpl_frame_list_next;
    jpl_frame_list_next = jpl_frame_list_next + 1u;
    if (jpl_frame_list_peak < h) {
      jpl_frame_list_peak = h;
    }
    if (jpl_frame_list_taken < JPL_REF_TOP) {
      jpl_frame_list_taken = jpl_frame_list_taken + 1u;
    }
  } else {
    if (jpl_frame_list_refused < JPL_REF_TOP) {
      jpl_frame_list_refused = jpl_frame_list_refused + 1u;
    }
  }
  return h;
}

jpl_ref jpl_frame_list_reset(void) {
  /* next >= 1u by construction, so this subtraction cannot wrap. */
  jpl_ref returned = jpl_frame_list_next - 1u;
  jpl_frame_list_next = 1u;
  return returned;
}

jpl_bool jpl_frame_list_is_live(jpl_ref h) {
  jpl_bool r = JPL_FALSE;
  if ((h != JPL_NIL) && (h < jpl_frame_list_next)) {
    r = JPL_TRUE;
  }
  return r;
}

/* ── §6.7's edge tables: one row per constructor (or per untagged cell), one class
   per word of the cell, in the cell's own field order.  The dimension is the
   header's own JPL_<stem>_NEDGE and the width under it is pinned to the cell's
   sizeof by jpl_check_<stem>_edge_covers_the_cell, so a table's length is a
   property of the cell it describes rather than of how many entries were typed.
   Every entry names its class; no bare number appears in a row. ── */
const jpl_nat jpl_word_edge[JPL_WORD_NEDGE] = {
  /* len + code[] */
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_SCALAR,
};

const jpl_nat jpl_pair_text_text_list_edge[JPL_PAIR_TEXT_TEXT_LIST_NEDGE] = {
  /* pair_text_text cell */
  JPL_EDGE_TO_WORD_POOL, JPL_EDGE_TO_WORD_POOL, JPL_EDGE_TO_PAIR_TEXT_TEXT_LIST_POOL,
};

const jpl_nat jpl_cmd_edge[JPL_CMD_NEDGE] = {
  /* Skip */
  JPL_EDGE_SCALAR, JPL_EDGE_UNUSED, JPL_EDGE_UNUSED, JPL_EDGE_UNUSED,
  /* Ext */
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_TO_TEXT_LIST_POOL, JPL_EDGE_UNUSED,
  /* Assign */
  JPL_EDGE_SCALAR, JPL_EDGE_TO_WORD_POOL, JPL_EDGE_TO_WORD_POOL, JPL_EDGE_UNUSED,
  /* Seq */
  JPL_EDGE_SCALAR, JPL_EDGE_TO_CMD_POOL, JPL_EDGE_TO_CMD_POOL, JPL_EDGE_UNUSED,
  /* And */
  JPL_EDGE_SCALAR, JPL_EDGE_TO_CMD_POOL, JPL_EDGE_TO_CMD_POOL, JPL_EDGE_UNUSED,
  /* Or */
  JPL_EDGE_SCALAR, JPL_EDGE_TO_CMD_POOL, JPL_EDGE_TO_CMD_POOL, JPL_EDGE_UNUSED,
  /* Bang */
  JPL_EDGE_SCALAR, JPL_EDGE_TO_CMD_POOL, JPL_EDGE_UNUSED, JPL_EDGE_UNUSED,
  /* If */
  JPL_EDGE_SCALAR, JPL_EDGE_TO_CMD_POOL, JPL_EDGE_TO_CMD_POOL, JPL_EDGE_TO_CMD_POOL,
  /* While */
  JPL_EDGE_SCALAR, JPL_EDGE_TO_CMD_POOL, JPL_EDGE_TO_CMD_POOL, JPL_EDGE_UNUSED,
  /* For */
  JPL_EDGE_SCALAR, JPL_EDGE_TO_WORD_POOL, JPL_EDGE_TO_TEXT_LIST_POOL, JPL_EDGE_TO_CMD_LIST_POOL,
  /* Case */
  JPL_EDGE_SCALAR, JPL_EDGE_TO_WORD_POOL, JPL_EDGE_TO_PAIR_TEXT_LIST_CMD_LIST_LIST_POOL, JPL_EDGE_UNUSED,
};

const jpl_nat jpl_text_list_edge[JPL_TEXT_LIST_NEDGE] = {
  /* text cell */
  JPL_EDGE_TO_WORD_POOL, JPL_EDGE_TO_TEXT_LIST_POOL,
};

const jpl_nat jpl_cmd_list_edge[JPL_CMD_LIST_NEDGE] = {
  /* cmd cell */
  JPL_EDGE_TO_CMD_POOL, JPL_EDGE_TO_CMD_LIST_POOL,
};

const jpl_nat jpl_pair_text_list_cmd_list_list_edge[JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_NEDGE] = {
  /* pair_text_list_cmd_list cell */
  JPL_EDGE_TO_TEXT_LIST_POOL, JPL_EDGE_TO_CMD_LIST_POOL, JPL_EDGE_TO_PAIR_TEXT_LIST_CMD_LIST_LIST_POOL,
};

const jpl_nat jpl_frame_edge[JPL_FRAME_NEDGE] = {
  /* FSeq */
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_TO_CMD_POOL, JPL_EDGE_UNUSED, JPL_EDGE_UNUSED,
  /* FAnd */
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_TO_CMD_POOL, JPL_EDGE_UNUSED, JPL_EDGE_UNUSED,
  /* FOr */
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_TO_CMD_POOL, JPL_EDGE_UNUSED, JPL_EDGE_UNUSED,
  /* FBang */
  JPL_EDGE_SCALAR, JPL_EDGE_UNUSED, JPL_EDGE_UNUSED, JPL_EDGE_UNUSED, JPL_EDGE_UNUSED,
  /* FIf */
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_TO_CMD_POOL, JPL_EDGE_TO_CMD_POOL, JPL_EDGE_UNUSED,
  /* FWhile */
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_TO_CMD_POOL, JPL_EDGE_TO_CMD_POOL, JPL_EDGE_UNUSED,
  /* FWhileBody */
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_TO_CMD_POOL, JPL_EDGE_TO_CMD_POOL, JPL_EDGE_UNUSED,
  /* FSeqList */
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_TO_CMD_LIST_POOL, JPL_EDGE_UNUSED, JPL_EDGE_UNUSED,
  /* FForRest */
  JPL_EDGE_SCALAR, JPL_EDGE_SCALAR, JPL_EDGE_TO_WORD_POOL, JPL_EDGE_TO_TEXT_LIST_POOL, JPL_EDGE_TO_CMD_LIST_POOL,
};

const jpl_nat jpl_frame_list_edge[JPL_FRAME_LIST_NEDGE] = {
  /* frame cell */
  JPL_EDGE_TO_FRAME_POOL, JPL_EDGE_TO_FRAME_LIST_POOL,
};

/* One saturating sum, so a breach has one readable place (§4.2).  Static on
   purpose: the only exported names are the per-pool ones the header declares. */
static jpl_nat jpl_pools_add_saturating(jpl_nat a, jpl_nat b) {
  jpl_nat r = a;
  if (r > (JPL_REF_TOP - b)) {
    r = JPL_REF_TOP;
  } else {
    r = r + b;
  }
  return r;
}

jpl_nat jpl_pools_refusals(void) {
  jpl_nat r = 0u;
  r = jpl_pools_add_saturating(r, jpl_word_refused);
  r = jpl_pools_add_saturating(r, jpl_pair_text_text_list_refused);
  r = jpl_pools_add_saturating(r, jpl_cmd_refused);
  r = jpl_pools_add_saturating(r, jpl_text_list_refused);
  r = jpl_pools_add_saturating(r, jpl_cmd_list_refused);
  r = jpl_pools_add_saturating(r, jpl_pair_text_list_cmd_list_list_refused);
  r = jpl_pools_add_saturating(r, jpl_frame_refused);
  r = jpl_pools_add_saturating(r, jpl_frame_list_refused);
  return r;
}
