/* sh_run_jpl_abi.h — the R8 instance ABI, rendered by the lowering census.
   GENERATED by verify/c/jpl_lower.ml from the vendored extraction
   (src/kernel/sh_run_c.ml{,i}) over roots mrun_c,step_c — DO NOT EDIT, and do not
   hand-write a body next to a declaration here.
   Every type name below is the rule the representation layer applied when it emitted
   sh_run_jpl.h, so this file is valid only AFTER that one:
     #include "sh_run_jpl.h"
   Declarations only: no function in this file has a body, and the ones marked OWED
   must not get one until JPL.md §6.3's model-side rewrite lands. */

#ifndef SH_RUN_JPL_ABI_H
#define SH_RUN_JPL_ABI_H

/* length : text -> nat
   instance 1, schema BOUNDED FOLD (non-tail)
   used by branch_guardb:4830, branch_guardb:4832, branch_need:4823, expand_c:4959, raw_bword:4572 */
jpl_nat jpl_length_1(jpl_wref a1);
/* declaration only: no body until the §6.3 rewrite for this schema lands
   (schema: BOUNDED FOLD (non-tail)) */

/* length : text list -> nat
   instance 2, schema BOUNDED FOLD (non-tail)
   used by branch_guardb:4831, enter_case_c:5016 */
jpl_nat jpl_length_2(jpl_text_list a1);
/* declaration only: no body until the §6.3 rewrite for this schema lands
   (schema: BOUNDED FOLD (non-tail)) */

/* rev : text -> text
   instance 1, schema BOUNDED FOLD (non-tail)
   used by ek_value:4889, expand_go:4899, expand_go:4900, expand_go:4908, expand_go:4912, expand_go:4931, expand_go:4940 */
jpl_wref jpl_rev_1(jpl_wref a1);
/* declaration only: no body until the §6.3 rewrite for this schema lands
   (schema: BOUNDED FOLD (non-tail)) */

/* rev_append : (text * text) list -> (text * text) list -> (text * text) list
   instance 1, schema structural tail loop
   used by setv_it:4855, setv_it:4859 */
jpl_pair_text_text_list jpl_rev_append_1(jpl_pair_text_text_list a1, jpl_pair_text_text_list a2);

/* rev_append : text -> text -> text
   instance 2, schema structural tail loop
   used by expand_go:4899, expand_go:4922, expand_go:4931, expand_go:4937, expand_go:4944 */
jpl_wref jpl_rev_append_2(jpl_wref a1, jpl_wref a2);

/* forallb : (text -> bool) -> text list -> bool
   instance 1, schema BOUNDED FOLD (non-tail)
   used by branch_guardb:4832 */
/* NOT EMITTED — jpl_forallb_1: its argument 1 is function-typed (text -> bool), so no C type names it and D-60411 forbids the only alternative — no function pointer is emitted here */

#endif /* SH_RUN_JPL_ABI_H */
