/* GENERATED by verify/c/jpl_emit.ml from
   src/kernel/sh_run_c.ml
   src/kernel/sh_run_c.mli
   DO NOT EDIT — the gate re-runs the emitter and byte-compares this file.
   JPL.md §6 is the normative contract; §9.2 decision 3 is why a recursive type
   is a handle into a static pool and never an inline array.  This is the TYPE
   LAYER only: no function body is emitted here, and JPL.5-B.3 owns the
   lowering into it.

   Three choices are NOT derived from the artifact, and layout.txt numbers them:
   which declared types are pooled, which cap sizes which list pool, and the
   pool headroom factor.  Everything else follows from a line of the .mli plus a
   capacity folded out of the .ml, and every struct's byte count is checked by
   the compiler through the typedef that follows it. */

#ifndef SH_RUN_JPL_H
#define SH_RUN_JPL_H

#include <stdint.h>

#define JPL_NIL 0u          /* the empty list */
#define JPL_FALSE 0u
#define JPL_TRUE 1u
#define JPL_NONE 0u         /* option tag   */
#define JPL_SOME 1u         /* option tag   */
#define JPL_BRES_OK 0u      /* sh_jpl.v §2  */
#define JPL_BRES_LIMIT 1u   /* saturate-to-error */

/* tags and slot meanings for cmd, from the artifact's declaration order.
   A pooled cell has one shape, so a constructor's arguments occupy
   consecutive slots and the tag says how many of them mean anything. */
#define JPL_CMD_SKIP 0u   /* Skip (no payload) */
#define JPL_CMD_EXT 1u   /* Ext of nat, text_list */
#define JPL_CMD_ASSIGN 2u   /* Assign of text, text */
#define JPL_CMD_SEQ 3u   /* Seq of cmd, cmd */
#define JPL_CMD_AND 4u   /* And of cmd, cmd */
#define JPL_CMD_OR 5u   /* Or of cmd, cmd */
#define JPL_CMD_BANG 6u   /* Bang of cmd */
#define JPL_CMD_IF 7u   /* If of cmd, cmd, cmd */
#define JPL_CMD_WHILE 8u   /* While of cmd, cmd */
#define JPL_CMD_FOR 9u   /* For of text, text_list, cmd_list */
#define JPL_CMD_CASE 10u   /* Case of text, pair_text_list_cmd_list_list */

/* tags and slot meanings for frame, from the artifact's declaration order.
   A pooled cell has one shape, so a constructor's arguments occupy
   consecutive slots and the tag says how many of them mean anything. */
#define JPL_FRAME_FSEQ 0u   /* FSeq of nat, cmd */
#define JPL_FRAME_FAND 1u   /* FAnd of nat, cmd */
#define JPL_FRAME_FOR 2u   /* FOr of nat, cmd */
#define JPL_FRAME_FBANG 3u   /* FBang (no payload) */
#define JPL_FRAME_FIF 4u   /* FIf of nat, cmd, cmd */
#define JPL_FRAME_FWHILE 5u   /* FWhile of nat, cmd, cmd */
#define JPL_FRAME_FWHILEBODY 6u   /* FWhileBody of nat, cmd, cmd */
#define JPL_FRAME_FSEQLIST 7u   /* FSeqList of nat, cmd_list */
#define JPL_FRAME_FFORREST 8u   /* FForRest of nat, text, text_list, cmd_list */

/* tags for out, in the artifact's own constructor order */
#define JPL_OUT_ONEXT 0u   /* cfg */
#define JPL_OUT_OEFFECT 1u   /* nat, text_list, stack, cstate */
#define JPL_OUT_ODONE 2u   /* cstate */
#define JPL_OUT_OLIMIT 3u   /* nullary */

/* tags for exp_mode, in the artifact's own constructor order */
#define JPL_EXP_MODE_EMAIN 0u
#define JPL_EXP_MODE_ENAME 1u
#define JPL_EXP_MODE_EBRACE 2u

/* tags for dres, in the artifact's own constructor order */
#define JPL_DRES_DDONE 0u   /* cstate */
#define JPL_DRES_DEFF 1u   /* nat, text_list, stack, cstate */
#define JPL_DRES_DLIM 2u   /* nullary */

/* ── capacities, constant-folded out of the artifact's own
   jpl_caps_table (sh_jpl.v §1.1).  No number in this section was written
   by hand: it is generated from the extracted term, and the gate diffs it
   against the artifact EVALUATED by the OCaml runtime. ── */
#define JPL_MAX_WIDTH 32u   /* MAX_WIDTH: bits in the fixed-width word */
#define JPL_MAX_WORD 256u   /* MAX_WORD: codes per word (text length) */
#define JPL_MAX_ARGV 64u   /* MAX_ARGV: argument words per simple command */
#define JPL_MAX_ENV 128u   /* MAX_ENV: simultaneously live shell variables */
#define JPL_MAX_LIST 1024u   /* MAX_LIST: any intermediate list length */
#define JPL_MAX_CMD 4096u   /* MAX_CMD: node pool for one lowered cmd tree */
#define JPL_MAX_STACK 8192u   /* MAX_STACK: explicit machine stack frames */
#define JPL_GLOB_FUEL 132353u   /* GLOB_FUEL: iterations of one full-width scan */
#define JPL_MAX_FUEL 136449u   /* MAX_FUEL: iterations the machine may run at all */

/* The total order sh_jpl.v §1 proves (cap_order, cap_fuel_order) and the
   two derived margins, re-checked in C so a cap that drifts fails the
   build and not only the proof. */
typedef char jpl_check_cap_order[((JPL_MAX_WIDTH <= JPL_MAX_WORD) && (JPL_MAX_ARGV <= JPL_MAX_ENV) && (JPL_MAX_ENV <= JPL_MAX_LIST) && (JPL_MAX_LIST <= JPL_MAX_CMD) && (JPL_MAX_CMD <= JPL_MAX_STACK)) ? 1 : -1];
typedef char jpl_check_cap_fuel_order[((JPL_MAX_STACK <= JPL_GLOB_FUEL) && (JPL_GLOB_FUEL <= JPL_MAX_FUEL)) ? 1 : -1];
typedef char jpl_check_cmd_is_the_fuel_margin[((JPL_MAX_CMD + JPL_GLOB_FUEL) == JPL_MAX_FUEL) ? 1 : -1];
typedef char jpl_check_stack_is_two_cmd_pools[((2u * JPL_MAX_CMD) == JPL_MAX_STACK) ? 1 : -1];
typedef char jpl_check_fuel_fits_the_word[(JPL_MAX_FUEL < 4294967295u) ? 1 : -1];

/* ── the fixed-width vocabulary, then the type layer in dependency order ── */
typedef uint32_t jpl_nat;   /* Coq nat after ExtrOcamlNatInt; every value is provably <= JPL_MAX_FUEL, so it cannot wrap */
typedef char jpl_check_word_is_the_declared_width[((8u * sizeof (jpl_nat)) == JPL_MAX_WIDTH) ? 1 : -1];
typedef uint32_t jpl_bool;   /* OCaml bool: 0 or 1; one word, so no cell needs padding */
typedef uint32_t jpl_unit;   /* OCaml unit: a value that carries no information */
typedef uint32_t jpl_ref;   /* pool handle; JPL_NIL is the empty list, index 0 is never allocated */
typedef jpl_ref jpl_wref;   /* a text VALUE is a word-slab index */
/* text = int list, bounded in LENGTH by MAX_WORD (sh_jpl.v §4's bword shape).
   The codes stay uint32_t: sh_concrete.v §1 only INTENDS each to be < 256, and
   an intent is not a lemma, so narrowing them here would be an unproved claim. */
typedef struct {
  jpl_nat wt_len;
  jpl_nat wt_code[JPL_MAX_WORD];
} jpl_text;
typedef char jpl_check_jpl_text_is_1028[((sizeof (jpl_text) == 1028u) ? 1 : -1)];
typedef struct {
  jpl_nat opt_tag;   /* text: JPL_NONE / JPL_SOME */
  jpl_wref opt_val;
} jpl_opt_text;
typedef char jpl_check_jpl_opt_text_is_8[((sizeof (jpl_opt_text) == 8u) ? 1 : -1)];
typedef struct {
  jpl_wref p_fst;   /* text */
  jpl_wref p_snd;   /* text */
} jpl_pair_text_text;
typedef char jpl_check_jpl_pair_text_text_is_8[((sizeof (jpl_pair_text_text) == 8u) ? 1 : -1)];
typedef jpl_ref jpl_pair_text_text_list;   /* pair_text_text list: index of the first cell, or JPL_NIL */
typedef struct {
  jpl_pair_text_text pair_text_text_list_hd;   /* the element, inline in the cell */
  jpl_ref pair_text_text_list_next;
} jpl_pair_text_text_list_cell;
typedef char jpl_check_jpl_pair_text_text_list_cell_is_12[((sizeof (jpl_pair_text_text_list_cell) == 12u) ? 1 : -1)];
typedef struct {
  jpl_wref bw_bytes;   /* text */
  jpl_nat bw_len;   /* nat */
} jpl_bword;
typedef char jpl_check_jpl_bword_is_8[((sizeof (jpl_bword) == 8u) ? 1 : -1)];
typedef struct {
  jpl_nat cstatus;   /* nat */
  jpl_pair_text_text_list cenv;   /* pair_text_text_list */
} jpl_cstate;
typedef char jpl_check_jpl_cstate_is_8[((sizeof (jpl_cstate) == 8u) ? 1 : -1)];
typedef jpl_ref jpl_cmd;   /* a cmd VALUE is a node-pool index */
typedef struct {
  jpl_nat cmd_tag;   /* one of JPL_CMD_* */
  jpl_nat cmd_slot0;
  jpl_nat cmd_slot1;
  jpl_nat cmd_slot2;
} jpl_cmd_node;
typedef char jpl_check_jpl_cmd_node_is_16[((sizeof (jpl_cmd_node) == 16u) ? 1 : -1)];
typedef jpl_ref jpl_text_list;   /* text list: index of the first cell, or JPL_NIL */
typedef struct {
  jpl_wref text_list_hd;   /* the element, inline in the cell */
  jpl_ref text_list_next;
} jpl_text_list_cell;
typedef char jpl_check_jpl_text_list_cell_is_8[((sizeof (jpl_text_list_cell) == 8u) ? 1 : -1)];
typedef jpl_ref jpl_cmd_list;   /* cmd list: index of the first cell, or JPL_NIL */
typedef struct {
  jpl_cmd cmd_list_hd;   /* the element, inline in the cell */
  jpl_ref cmd_list_next;
} jpl_cmd_list_cell;
typedef char jpl_check_jpl_cmd_list_cell_is_8[((sizeof (jpl_cmd_list_cell) == 8u) ? 1 : -1)];
typedef struct {
  jpl_text_list p_fst;   /* text_list */
  jpl_cmd_list p_snd;   /* cmd_list */
} jpl_pair_text_list_cmd_list;
typedef char jpl_check_jpl_pair_text_list_cmd_list_is_8[((sizeof (jpl_pair_text_list_cmd_list) == 8u) ? 1 : -1)];
typedef jpl_ref jpl_pair_text_list_cmd_list_list;   /* pair_text_list_cmd_list list: index of the first cell, or JPL_NIL */
typedef struct {
  jpl_pair_text_list_cmd_list pair_text_list_cmd_list_list_hd;   /* the element, inline in the cell */
  jpl_ref pair_text_list_cmd_list_list_next;
} jpl_pair_text_list_cmd_list_list_cell;
typedef char jpl_check_jpl_pair_text_list_cmd_list_list_cell_is_12[((sizeof (jpl_pair_text_list_cmd_list_list_cell) == 12u) ? 1 : -1)];
typedef struct {
  jpl_nat opt_tag;   /* cmd: JPL_NONE / JPL_SOME */
  jpl_cmd opt_val;
} jpl_opt_cmd;
typedef char jpl_check_jpl_opt_cmd_is_8[((sizeof (jpl_opt_cmd) == 8u) ? 1 : -1)];
typedef jpl_ref jpl_frame;   /* a frame VALUE is a node-pool index */
typedef struct {
  jpl_nat frame_tag;   /* one of JPL_FRAME_* */
  jpl_nat frame_slot0;
  jpl_nat frame_slot1;
  jpl_nat frame_slot2;
  jpl_nat frame_slot3;
} jpl_frame_node;
typedef char jpl_check_jpl_frame_node_is_20[((sizeof (jpl_frame_node) == 20u) ? 1 : -1)];
typedef jpl_ref jpl_frame_list;   /* frame list: index of the first cell, or JPL_NIL */
typedef struct {
  jpl_frame frame_list_hd;   /* the element, inline in the cell */
  jpl_ref frame_list_next;
} jpl_frame_list_cell;
typedef char jpl_check_jpl_frame_list_cell_is_8[((sizeof (jpl_frame_list_cell) == 8u) ? 1 : -1)];
typedef struct {
  jpl_nat cf;   /* nat */
  jpl_opt_cmd cc;   /* opt_cmd */
  jpl_frame_list ck;   /* stack */
  jpl_cstate cs;   /* cstate */
} jpl_cfg;
typedef char jpl_check_jpl_cfg_is_24[((sizeof (jpl_cfg) == 24u) ? 1 : -1)];
typedef struct {   /* Onext of out */
  jpl_cfg a0;   /* cfg */
} jpl_out_Onext;
typedef char jpl_check_jpl_out_Onext_is_24[((sizeof (jpl_out_Onext) == 24u) ? 1 : -1)];
typedef struct {   /* Oeffect of out */
  jpl_nat a0;   /* nat */
  jpl_text_list a1;   /* text_list */
  jpl_frame_list a2;   /* stack */
  jpl_cstate a3;   /* cstate */
} jpl_out_Oeffect;
typedef char jpl_check_jpl_out_Oeffect_is_20[((sizeof (jpl_out_Oeffect) == 20u) ? 1 : -1)];
typedef struct {   /* Odone of out */
  jpl_cstate a0;   /* cstate */
} jpl_out_Odone;
typedef char jpl_check_jpl_out_Odone_is_8[((sizeof (jpl_out_Odone) == 8u) ? 1 : -1)];
/* No union (JPL forbids them), so every constructor's payload is present and
   the tag selects which ones mean anything.  Returned and stored by value. */
typedef struct {
  jpl_nat out_tag;   /* one of JPL_OUT_* */
  jpl_out_Onext out_Onext;
  jpl_out_Oeffect out_Oeffect;
  jpl_out_Odone out_Odone;
} jpl_out;
typedef char jpl_check_jpl_out_is_56[((sizeof (jpl_out) == 56u) ? 1 : -1)];
typedef struct {
  jpl_nat opt_tag;   /* pair_text_text: JPL_NONE / JPL_SOME */
  jpl_pair_text_text opt_val;
} jpl_opt_pair_text_text;
typedef char jpl_check_jpl_opt_pair_text_text_is_12[((sizeof (jpl_opt_pair_text_text) == 12u) ? 1 : -1)];
typedef struct {
  jpl_nat opt_tag;   /* pair_text_text_list: JPL_NONE / JPL_SOME */
  jpl_pair_text_text_list opt_val;
} jpl_opt_pair_text_text_list;
typedef char jpl_check_jpl_opt_pair_text_text_list_is_8[((sizeof (jpl_opt_pair_text_text_list) == 8u) ? 1 : -1)];
typedef uint32_t jpl_exp_mode;   /* variant of 3 nullary constructors */
typedef struct {
  jpl_exp_mode ek_mode;   /* exp_mode */
  jpl_wref ek_inp;   /* text */
  jpl_wref ek_out;   /* text */
  jpl_wref ek_name;   /* text */
} jpl_exp_k;
typedef char jpl_check_jpl_exp_k_is_16[((sizeof (jpl_exp_k) == 16u) ? 1 : -1)];
typedef struct {
  jpl_nat bres_tag;   /* bword: JPL_BRES_OK / JPL_BRES_LIMIT */
  jpl_bword bres_val;
} jpl_bres_bword;
typedef char jpl_check_jpl_bres_bword_is_12[((sizeof (jpl_bres_bword) == 12u) ? 1 : -1)];
typedef struct {
  jpl_nat opt_tag;   /* cstate: JPL_NONE / JPL_SOME */
  jpl_cstate opt_val;
} jpl_opt_cstate;
typedef char jpl_check_jpl_opt_cstate_is_12[((sizeof (jpl_opt_cstate) == 12u) ? 1 : -1)];
typedef struct {   /* DDone of dres */
  jpl_cstate a0;   /* cstate */
} jpl_dres_DDone;
typedef char jpl_check_jpl_dres_DDone_is_8[((sizeof (jpl_dres_DDone) == 8u) ? 1 : -1)];
typedef struct {   /* DEff of dres */
  jpl_nat a0;   /* nat */
  jpl_text_list a1;   /* text_list */
  jpl_frame_list a2;   /* stack */
  jpl_cstate a3;   /* cstate */
} jpl_dres_DEff;
typedef char jpl_check_jpl_dres_DEff_is_20[((sizeof (jpl_dres_DEff) == 20u) ? 1 : -1)];
/* No union (JPL forbids them), so every constructor's payload is present and
   the tag selects which ones mean anything.  Returned and stored by value. */
typedef struct {
  jpl_nat dres_tag;   /* one of JPL_DRES_* */
  jpl_dres_DDone dres_DDone;
  jpl_dres_DEff dres_DEff;
} jpl_dres;
typedef char jpl_check_jpl_dres_is_32[((sizeof (jpl_dres) == 32u) ? 1 : -1)];
typedef char jpl_check_one_word_families[((sizeof (jpl_nat) == 4u) && (sizeof (jpl_bool) == 4u) && (sizeof (jpl_unit) == 4u) && (sizeof (jpl_ref) == 4u) && (sizeof (jpl_wref) == 4u) && (sizeof (jpl_pair_text_text_list) == 4u) && (sizeof (jpl_cmd) == 4u) && (sizeof (jpl_text_list) == 4u) && (sizeof (jpl_cmd_list) == 4u) && (sizeof (jpl_pair_text_list_cmd_list_list) == 4u) && (sizeof (jpl_frame) == 4u) && (sizeof (jpl_frame_list) == 4u) && (sizeof (jpl_exp_mode) == 4u) ? 1 : -1)];

/* ── the pools.  Definitions live in the emitted translation unit
   (JPL.md §6: no dynamic allocation); they are declared here so every
   consumer compiles against one capacity.  Index 0 is JPL_NIL and is
   never allocated, so a capacity counts the reserved cell too. ── */
/* PENDING CAPACITY — jpl_word_pool is declared, and nothing sizes it:
words are reachable from cmd nodes (Ext, For and Case patterns hold them),
    so they are bounded only by a PRODUCT of caps, and no entry of the LOCKED
    cap table is the capacity of a word.  The model has to add one (see the
    report's range) before this array can be sized; inventing a dimension here
    would be the parallel encoding this pipeline retires. */
extern jpl_text jpl_word_pool[];

#define JPL_POOL_PAIR_TEXT_TEXT_LIST 256u   /* from JPL_MAX_ENV, 128 cells, x headroom 2; the environment's pair list (sh_jpl.v §5 wf_benv) */
extern jpl_pair_text_text_list_cell jpl_pair_text_text_list_pool[JPL_POOL_PAIR_TEXT_TEXT_LIST];

#define JPL_POOL_TEXT_LIST 2048u   /* from JPL_MAX_LIST, 1024 cells, x headroom 2; an intermediate list (sh_jpl.v §1 MAX_LIST) */
extern jpl_text_list_cell jpl_text_list_pool[JPL_POOL_TEXT_LIST];

#define JPL_POOL_CMD_LIST 2048u   /* from JPL_MAX_LIST, 1024 cells, x headroom 2; an intermediate list (sh_jpl.v §1 MAX_LIST) */
extern jpl_cmd_list_cell jpl_cmd_list_pool[JPL_POOL_CMD_LIST];

#define JPL_POOL_PAIR_TEXT_LIST_CMD_LIST_LIST 2048u   /* from JPL_MAX_LIST, 1024 cells, x headroom 2; an intermediate list (sh_jpl.v §1 MAX_LIST) */
extern jpl_pair_text_list_cmd_list_list_cell jpl_pair_text_list_cmd_list_list_pool[JPL_POOL_PAIR_TEXT_LIST_CMD_LIST_LIST];

#define JPL_POOL_FRAME_LIST 16384u   /* from JPL_MAX_STACK, 8192 cells, x headroom 2; the machine stack = frame list */
extern jpl_frame_list_cell jpl_frame_list_pool[JPL_POOL_FRAME_LIST];


/* ── prototypes for the shipped closure: parameter names are the artifact's
   own, and every type comes from the .mli signature mapped by the rule set. */
/* PENDING polymorphic length : 'a1 list -> int
   reached from 6 closure bindings; a C instance must be chosen per call
   site, so JPL.md §6's "no monomorphization" claim is refuted by this
   binding and the instance set belongs to JPL.5-B.3's call-site census. */
/* PENDING polymorphic app : 'a1 list -> 'a1 list -> 'a1 list
   reached from 2 closure bindings; a C instance must be chosen per call
   site, so JPL.md §6's "no monomorphization" claim is refuted by this
   binding and the instance set belongs to JPL.5-B.3's call-site census. */
jpl_nat jpl_add(jpl_nat a0, jpl_nat a1);
jpl_nat jpl_mul(jpl_nat a0, jpl_nat a1);
/* PENDING polymorphic rev : 'a1 list -> 'a1 list
   reached from 3 closure bindings; a C instance must be chosen per call
   site, so JPL.md §6's "no monomorphization" claim is refuted by this
   binding and the instance set belongs to JPL.5-B.3's call-site census. */
/* PENDING polymorphic rev_append : 'a1 list -> 'a1 list -> 'a1 list
   reached from 3 closure bindings; a C instance must be chosen per call
   site, so JPL.md §6's "no monomorphization" claim is refuted by this
   binding and the instance set belongs to JPL.5-B.3's call-site census. */
/* PENDING polymorphic forallb : ('a1 -> bool) -> 'a1 list -> bool
   reached from 2 closure bindings; a C instance must be chosen per call
   site, so JPL.md §6's "no monomorphization" claim is refuted by this
   binding and the instance set belongs to JPL.5-B.3's call-site census. */
jpl_bool jpl_teqb(jpl_wref s1, jpl_wref s2);
jpl_nat jpl_bstat(jpl_nat n);
jpl_opt_text jpl_getv(jpl_wref a0, jpl_pair_text_text_list a1);
#define JPL_C_B_DOLLAR 36u   /* b_dollar : int */
#define JPL_C_B_LBRACE 123u   /* b_lbrace : int */
#define JPL_C_B_RBRACE 125u   /* b_rbrace : int */
#define JPL_C_B_QMARK 63u   /* b_qmark : int */
#define JPL_C_B_USCORE 95u   /* b_uscore : int */
#define JPL_C_B_0 48u   /* b_0 : int */
jpl_bool jpl_is_digit(jpl_nat b);
jpl_bool jpl_is_alpha(jpl_nat b);
jpl_bool jpl_is_name(jpl_nat b);
jpl_wref jpl_nat_digits(jpl_nat f, jpl_nat n, jpl_wref acc);
jpl_wref jpl_nat2text(jpl_nat n);
#define JPL_C_B_STAR 42u   /* b_star : int */
/* mAX_WORD : int = 256 is already defined above as JPL_MAX_WORD — one number, one
   name, so the cap the C allocates against is the cap the artifact carries. */
/* mAX_LIST : int = 1024 is already defined above as JPL_MAX_LIST — one number, one
   name, so the cap the C allocates against is the cap the artifact carries. */
/* gLOB_FUEL : int = 132353 is already defined above as JPL_GLOB_FUEL — one number, one
   name, so the cap the C allocates against is the cap the artifact carries. */
/* mAX_FUEL : int = 136449 is already defined above as JPL_MAX_FUEL — one number, one
   name, so the cap the C allocates against is the cap the artifact carries. */
jpl_bword jpl_raw_bword(jpl_wref l);
jpl_bool jpl_isz(jpl_cstate s);
jpl_out jpl_enter_seq(jpl_nat h, jpl_cmd_list l, jpl_cstate s, jpl_frame_list k);
jpl_bool jpl_glob_it(jpl_nat f, jpl_wref pat, jpl_wref str, jpl_opt_pair_text_text bk);
jpl_bool jpl_glob_iter(jpl_nat f, jpl_wref pat, jpl_wref str);
jpl_bool jpl_match_any_iter(jpl_nat f, jpl_text_list pats, jpl_wref scrut);
jpl_nat jpl_branch_need(jpl_text_list pats, jpl_wref w);
jpl_bool jpl_branch_guardb(jpl_nat g, jpl_text_list pats, jpl_wref w);
jpl_opt_pair_text_text_list jpl_setv_it(jpl_nat f, jpl_wref k, jpl_wref v, jpl_pair_text_text_list acc, jpl_pair_text_text_list m);
jpl_wref jpl_ek_value(jpl_pair_text_text_list m, jpl_wref nm);
jpl_wref jpl_expand_go(jpl_nat f, jpl_pair_text_text_list m, jpl_nat st, jpl_exp_k k);
jpl_wref jpl_expand_it(jpl_nat f, jpl_pair_text_text_list m, jpl_nat st, jpl_wref inp);
jpl_bres_bword jpl_expand_c(jpl_nat f, jpl_pair_text_text_list m, jpl_nat st, jpl_wref inp);
jpl_out jpl_assign_c(jpl_wref nm, jpl_wref val0, jpl_frame_list k, jpl_cstate s);
jpl_opt_cstate jpl_bind_word_o(jpl_nat g, jpl_wref var, jpl_wref w, jpl_cstate s);
jpl_out jpl_enter_for_c(jpl_nat h, jpl_wref var, jpl_text_list ws, jpl_cmd_list body, jpl_cstate s, jpl_frame_list k);
jpl_out jpl_enter_case_c(jpl_nat h, jpl_wref scrut, jpl_pair_text_list_cmd_list_list brs, jpl_cstate s, jpl_frame_list k);
jpl_out jpl_step_cmd_c(jpl_nat f, jpl_cmd c, jpl_frame_list k, jpl_cstate s);
jpl_out jpl_step_ret_c(jpl_frame_list k, jpl_cstate s);
jpl_out jpl_step_c(jpl_cfg g);
jpl_dres jpl_mrun_c(jpl_nat b, jpl_cfg g);

#endif /* SH_RUN_JPL_H */
