/* GENERATED by verify/c/jpl_emit.ml from
   src/kernel/sh_run_c.ml
   src/kernel/sh_run_c.mli
   DO NOT EDIT — the gate re-runs the emitter and byte-compares this file.
   JPL.md §6 is the normative contract; §9.2 decision 3 is why a recursive type
   is a handle into a static pool and never an inline array.  This is the TYPE
   LAYER only: no function body is emitted here, and JPL.5-B.3 owns the
   lowering into it.  The pool runtime below (JPL.md §6.6) is declarations only
   as well: the pool arrays themselves and the allocator bodies are in the
   generated translation unit sh_run_jpl_pools.c, which includes this header.

   Three choices are NOT derived from the artifact, and layout.txt numbers them:
   which declared types are pooled, which cap sizes which list pool, and the
   pool headroom factor.  Everything else follows from a line of the .mli plus a
   capacity folded out of the .ml, and every struct's byte count is checked by
   the compiler through the typedef that follows it. */

#ifndef SH_RUN_JPL_H
#define SH_RUN_JPL_H

#include <stdint.h>

#define JPL_NIL 0u          /* the empty list */
#define JPL_FALSE 0u
#define JPL_TRUE 1u
#define JPL_NONE 0u         /* option tag   */
#define JPL_SOME 1u         /* option tag   */
#define JPL_BRES_OK 0u      /* sh_jpl.v §2  */
#define JPL_BRES_LIMIT 1u   /* saturate-to-error */

/* tags and slot meanings for cmd, from the artifact's declaration order.
   A pooled cell has one shape, so a constructor's arguments occupy
   consecutive slots and the tag says how many of them mean anything. */
#define JPL_CMD_SKIP 0u   /* Skip (no payload) */
#define JPL_CMD_EXT 1u   /* Ext of nat, text_list */
#define JPL_CMD_ASSIGN 2u   /* Assign of text, text */
#define JPL_CMD_SEQ 3u   /* Seq of cmd, cmd */
#define JPL_CMD_AND 4u   /* And of cmd, cmd */
#define JPL_CMD_OR 5u   /* Or of cmd, cmd */
#define JPL_CMD_BANG 6u   /* Bang of cmd */
#define JPL_CMD_IF 7u   /* If of cmd, cmd, cmd */
#define JPL_CMD_WHILE 8u   /* While of cmd, cmd */
#define JPL_CMD_FOR 9u   /* For of text, text_list, cmd_list */
#define JPL_CMD_CASE 10u   /* Case of text, pair_text_list_cmd_list_list */

/* tags and slot meanings for frame, from the artifact's declaration order.
   A pooled cell has one shape, so a constructor's arguments occupy
   consecutive slots and the tag says how many of them mean anything. */
#define JPL_FRAME_FSEQ 0u   /* FSeq of nat, cmd */
#define JPL_FRAME_FAND 1u   /* FAnd of nat, cmd */
#define JPL_FRAME_FOR 2u   /* FOr of nat, cmd */
#define JPL_FRAME_FBANG 3u   /* FBang (no payload) */
#define JPL_FRAME_FIF 4u   /* FIf of nat, cmd, cmd */
#define JPL_FRAME_FWHILE 5u   /* FWhile of nat, cmd, cmd */
#define JPL_FRAME_FWHILEBODY 6u   /* FWhileBody of nat, cmd, cmd */
#define JPL_FRAME_FSEQLIST 7u   /* FSeqList of nat, cmd_list */
#define JPL_FRAME_FFORREST 8u   /* FForRest of nat, text, text_list, cmd_list */

/* tags for out, in the artifact's own constructor order */
#define JPL_OUT_ONEXT 0u   /* cfg */
#define JPL_OUT_OEFFECT 1u   /* nat, text_list, stack, cstate */
#define JPL_OUT_ODONE 2u   /* cstate */
#define JPL_OUT_OLIMIT 3u   /* nullary */

/* tags for exp_mode, in the artifact's own constructor order */
#define JPL_EXP_MODE_EMAIN 0u
#define JPL_EXP_MODE_ENAME 1u
#define JPL_EXP_MODE_EBRACE 2u

/* tags for dres, in the artifact's own constructor order */
#define JPL_DRES_DDONE 0u   /* cstate */
#define JPL_DRES_DEFF 1u   /* nat, text_list, stack, cstate */
#define JPL_DRES_DLIM 2u   /* nullary */

/* ── capacities, constant-folded out of the artifact's own
   jpl_caps_table (sh_jpl.v §1.1).  No number in this section was written
   by hand: it is generated from the extracted term, and the gate diffs it
   against the artifact EVALUATED by the OCaml runtime. ── */
#define JPL_MAX_WIDTH 32u   /* MAX_WIDTH: bits in the fixed-width word */
#define JPL_MAX_WORD 256u   /* MAX_WORD: codes per word (text length) */
#define JPL_MAX_ARGV 64u   /* MAX_ARGV: argument words per simple command */
#define JPL_MAX_ENV 128u   /* MAX_ENV: simultaneously live shell variables */
#define JPL_MAX_LIST 1024u   /* MAX_LIST: any intermediate list length */
#define JPL_MAX_CMD 4096u   /* MAX_CMD: node pool for one lowered cmd tree */
#define JPL_MAX_STACK 8192u   /* MAX_STACK: explicit machine stack frames */
#define JPL_MAX_WORDS 16642u   /* MAX_WORDS: word (text) cells in the slab */
#define JPL_GLOB_FUEL 132353u   /* GLOB_FUEL: iterations of one full-width scan */
#define JPL_MAX_FUEL 136449u   /* MAX_FUEL: iterations the machine may run at all */

/* The total order sh_jpl.v §1 proves (cap_order, cap_words_order, cap_fuel_order)
   and the two derived margins, re-checked in C so a cap that drifts fails the
   build and not only the proof.  The last check is the one that matters for the
   word slab: MAX_WORDS is not an independent number, it is the sum §1 names, so
   the C macro is pinned against its own decomposition. */
typedef char jpl_check_cap_order[((JPL_MAX_WIDTH <= JPL_MAX_WORD) && (JPL_MAX_ARGV <= JPL_MAX_ENV) && (JPL_MAX_ENV <= JPL_MAX_LIST) && (JPL_MAX_LIST <= JPL_MAX_CMD) && (JPL_MAX_CMD <= JPL_MAX_STACK)) ? 1 : -1];
typedef char jpl_check_cap_fuel_order[((JPL_MAX_STACK <= JPL_GLOB_FUEL) && (JPL_GLOB_FUEL <= JPL_MAX_FUEL)) ? 1 : -1];
typedef char jpl_check_cmd_is_the_fuel_margin[((JPL_MAX_CMD + JPL_GLOB_FUEL) == JPL_MAX_FUEL) ? 1 : -1];
typedef char jpl_check_stack_is_two_cmd_pools[((2u * JPL_MAX_CMD) == JPL_MAX_STACK) ? 1 : -1];
typedef char jpl_check_words_is_the_named_sum[((2u * JPL_MAX_STACK + 2u * JPL_MAX_ENV + 2u) == JPL_MAX_WORDS) ? 1 : -1];
typedef char jpl_check_words_order[((JPL_MAX_STACK <= JPL_MAX_WORDS) && (JPL_MAX_WORDS <= JPL_GLOB_FUEL)) ? 1 : -1];
typedef char jpl_check_fuel_fits_the_word[(JPL_MAX_FUEL < 4294967295u) ? 1 : -1];

/* ── the fixed-width vocabulary, then the type layer in dependency order ── */
typedef uint32_t jpl_nat;   /* Coq nat after ExtrOcamlNatInt; every value is provably <= JPL_MAX_FUEL, so it cannot wrap */
typedef char jpl_check_word_is_the_declared_width[((8u * sizeof (jpl_nat)) == JPL_MAX_WIDTH) ? 1 : -1];
typedef uint32_t jpl_bool;   /* OCaml bool: 0 or 1; one word, so no cell needs padding */
typedef uint32_t jpl_unit;   /* OCaml unit: a value that carries no information */
typedef uint32_t jpl_ref;   /* pool handle; JPL_NIL is the empty list, index 0 is never allocated */
typedef jpl_ref jpl_wref;   /* a text VALUE is a word-slab index */
/* text = int list, bounded in LENGTH by MAX_WORD (sh_jpl.v §4's bword shape).
   The codes stay uint32_t: sh_concrete.v §1 only INTENDS each to be < 256, and
   an intent is not a lemma, so narrowing them here would be an unproved claim. */
typedef struct {
  jpl_nat wt_len;
  jpl_nat wt_code[JPL_MAX_WORD];
} jpl_text;
typedef char jpl_check_jpl_text_is_1028[((sizeof (jpl_text) == 1028u) ? 1 : -1)];
typedef struct {
  jpl_nat opt_tag;   /* text: JPL_NONE / JPL_SOME */
  jpl_wref opt_val;
} jpl_opt_text;
typedef char jpl_check_jpl_opt_text_is_8[((sizeof (jpl_opt_text) == 8u) ? 1 : -1)];
typedef struct {
  jpl_wref p_fst;   /* text */
  jpl_wref p_snd;   /* text */
} jpl_pair_text_text;
typedef char jpl_check_jpl_pair_text_text_is_8[((sizeof (jpl_pair_text_text) == 8u) ? 1 : -1)];
typedef jpl_ref jpl_pair_text_text_list;   /* pair_text_text list: index of the first cell, or JPL_NIL */
typedef struct {
  jpl_pair_text_text pair_text_text_list_hd;   /* the element, inline in the cell */
  jpl_ref pair_text_text_list_next;
} jpl_pair_text_text_list_cell;
typedef char jpl_check_jpl_pair_text_text_list_cell_is_12[((sizeof (jpl_pair_text_text_list_cell) == 12u) ? 1 : -1)];
typedef struct {
  jpl_wref bw_bytes;   /* text */
  jpl_nat bw_len;   /* nat */
} jpl_bword;
typedef char jpl_check_jpl_bword_is_8[((sizeof (jpl_bword) == 8u) ? 1 : -1)];
typedef struct {
  jpl_nat cstatus;   /* nat */
  jpl_pair_text_text_list cenv;   /* pair_text_text_list */
} jpl_cstate;
typedef char jpl_check_jpl_cstate_is_8[((sizeof (jpl_cstate) == 8u) ? 1 : -1)];
typedef jpl_ref jpl_cmd;   /* a cmd VALUE is a node-pool index */
typedef struct {
  jpl_nat cmd_tag;   /* one of JPL_CMD_* */
  jpl_nat cmd_slot0;
  jpl_nat cmd_slot1;
  jpl_nat cmd_slot2;
} jpl_cmd_node;
typedef char jpl_check_jpl_cmd_node_is_16[((sizeof (jpl_cmd_node) == 16u) ? 1 : -1)];
typedef jpl_ref jpl_text_list;   /* text list: index of the first cell, or JPL_NIL */
typedef struct {
  jpl_wref text_list_hd;   /* the element, inline in the cell */
  jpl_ref text_list_next;
} jpl_text_list_cell;
typedef char jpl_check_jpl_text_list_cell_is_8[((sizeof (jpl_text_list_cell) == 8u) ? 1 : -1)];
typedef jpl_ref jpl_cmd_list;   /* cmd list: index of the first cell, or JPL_NIL */
typedef struct {
  jpl_cmd cmd_list_hd;   /* the element, inline in the cell */
  jpl_ref cmd_list_next;
} jpl_cmd_list_cell;
typedef char jpl_check_jpl_cmd_list_cell_is_8[((sizeof (jpl_cmd_list_cell) == 8u) ? 1 : -1)];
typedef struct {
  jpl_text_list p_fst;   /* text_list */
  jpl_cmd_list p_snd;   /* cmd_list */
} jpl_pair_text_list_cmd_list;
typedef char jpl_check_jpl_pair_text_list_cmd_list_is_8[((sizeof (jpl_pair_text_list_cmd_list) == 8u) ? 1 : -1)];
typedef jpl_ref jpl_pair_text_list_cmd_list_list;   /* pair_text_list_cmd_list list: index of the first cell, or JPL_NIL */
typedef struct {
  jpl_pair_text_list_cmd_list pair_text_list_cmd_list_list_hd;   /* the element, inline in the cell */
  jpl_ref pair_text_list_cmd_list_list_next;
} jpl_pair_text_list_cmd_list_list_cell;
typedef char jpl_check_jpl_pair_text_list_cmd_list_list_cell_is_12[((sizeof (jpl_pair_text_list_cmd_list_list_cell) == 12u) ? 1 : -1)];
typedef struct {
  jpl_nat opt_tag;   /* cmd: JPL_NONE / JPL_SOME */
  jpl_cmd opt_val;
} jpl_opt_cmd;
typedef char jpl_check_jpl_opt_cmd_is_8[((sizeof (jpl_opt_cmd) == 8u) ? 1 : -1)];
typedef jpl_ref jpl_frame;   /* a frame VALUE is a node-pool index */
typedef struct {
  jpl_nat frame_tag;   /* one of JPL_FRAME_* */
  jpl_nat frame_slot0;
  jpl_nat frame_slot1;
  jpl_nat frame_slot2;
  jpl_nat frame_slot3;
} jpl_frame_node;
typedef char jpl_check_jpl_frame_node_is_20[((sizeof (jpl_frame_node) == 20u) ? 1 : -1)];
typedef jpl_ref jpl_frame_list;   /* frame list: index of the first cell, or JPL_NIL */
typedef struct {
  jpl_frame frame_list_hd;   /* the element, inline in the cell */
  jpl_ref frame_list_next;
} jpl_frame_list_cell;
typedef char jpl_check_jpl_frame_list_cell_is_8[((sizeof (jpl_frame_list_cell) == 8u) ? 1 : -1)];
typedef struct {
  jpl_nat cf;   /* nat */
  jpl_opt_cmd cc;   /* opt_cmd */
  jpl_frame_list ck;   /* stack */
  jpl_cstate cs;   /* cstate */
} jpl_cfg;
typedef char jpl_check_jpl_cfg_is_24[((sizeof (jpl_cfg) == 24u) ? 1 : -1)];
typedef struct {   /* Onext of out */
  jpl_cfg a0;   /* cfg */
} jpl_out_Onext;
typedef char jpl_check_jpl_out_Onext_is_24[((sizeof (jpl_out_Onext) == 24u) ? 1 : -1)];
typedef struct {   /* Oeffect of out */
  jpl_nat a0;   /* nat */
  jpl_text_list a1;   /* text_list */
  jpl_frame_list a2;   /* stack */
  jpl_cstate a3;   /* cstate */
} jpl_out_Oeffect;
typedef char jpl_check_jpl_out_Oeffect_is_20[((sizeof (jpl_out_Oeffect) == 20u) ? 1 : -1)];
typedef struct {   /* Odone of out */
  jpl_cstate a0;   /* cstate */
} jpl_out_Odone;
typedef char jpl_check_jpl_out_Odone_is_8[((sizeof (jpl_out_Odone) == 8u) ? 1 : -1)];
/* No union (JPL forbids them), so every constructor's payload is present and
   the tag selects which ones mean anything.  Returned and stored by value. */
typedef struct {
  jpl_nat out_tag;   /* one of JPL_OUT_* */
  jpl_out_Onext out_Onext;
  jpl_out_Oeffect out_Oeffect;
  jpl_out_Odone out_Odone;
} jpl_out;
typedef char jpl_check_jpl_out_is_56[((sizeof (jpl_out) == 56u) ? 1 : -1)];
typedef struct {
  jpl_nat opt_tag;   /* pair_text_text: JPL_NONE / JPL_SOME */
  jpl_pair_text_text opt_val;
} jpl_opt_pair_text_text;
typedef char jpl_check_jpl_opt_pair_text_text_is_12[((sizeof (jpl_opt_pair_text_text) == 12u) ? 1 : -1)];
typedef struct {
  jpl_nat opt_tag;   /* pair_text_text_list: JPL_NONE / JPL_SOME */
  jpl_pair_text_text_list opt_val;
} jpl_opt_pair_text_text_list;
typedef char jpl_check_jpl_opt_pair_text_text_list_is_8[((sizeof (jpl_opt_pair_text_text_list) == 8u) ? 1 : -1)];
typedef uint32_t jpl_exp_mode;   /* variant of 3 nullary constructors */
typedef struct {
  jpl_exp_mode ek_mode;   /* exp_mode */
  jpl_wref ek_inp;   /* text */
  jpl_wref ek_out;   /* text */
  jpl_wref ek_name;   /* text */
} jpl_exp_k;
typedef char jpl_check_jpl_exp_k_is_16[((sizeof (jpl_exp_k) == 16u) ? 1 : -1)];
typedef struct {
  jpl_nat bres_tag;   /* bword: JPL_BRES_OK / JPL_BRES_LIMIT */
  jpl_bword bres_val;
} jpl_bres_bword;
typedef char jpl_check_jpl_bres_bword_is_12[((sizeof (jpl_bres_bword) == 12u) ? 1 : -1)];
typedef struct {
  jpl_nat opt_tag;   /* cstate: JPL_NONE / JPL_SOME */
  jpl_cstate opt_val;
} jpl_opt_cstate;
typedef char jpl_check_jpl_opt_cstate_is_12[((sizeof (jpl_opt_cstate) == 12u) ? 1 : -1)];
typedef struct {   /* DDone of dres */
  jpl_cstate a0;   /* cstate */
} jpl_dres_DDone;
typedef char jpl_check_jpl_dres_DDone_is_8[((sizeof (jpl_dres_DDone) == 8u) ? 1 : -1)];
typedef struct {   /* DEff of dres */
  jpl_nat a0;   /* nat */
  jpl_text_list a1;   /* text_list */
  jpl_frame_list a2;   /* stack */
  jpl_cstate a3;   /* cstate */
} jpl_dres_DEff;
typedef char jpl_check_jpl_dres_DEff_is_20[((sizeof (jpl_dres_DEff) == 20u) ? 1 : -1)];
/* No union (JPL forbids them), so every constructor's payload is present and
   the tag selects which ones mean anything.  Returned and stored by value. */
typedef struct {
  jpl_nat dres_tag;   /* one of JPL_DRES_* */
  jpl_dres_DDone dres_DDone;
  jpl_dres_DEff dres_DEff;
} jpl_dres;
typedef char jpl_check_jpl_dres_is_32[((sizeof (jpl_dres) == 32u) ? 1 : -1)];
typedef char jpl_check_one_word_families[((sizeof (jpl_nat) == 4u) && (sizeof (jpl_bool) == 4u) && (sizeof (jpl_unit) == 4u) && (sizeof (jpl_ref) == 4u) && (sizeof (jpl_wref) == 4u) && (sizeof (jpl_pair_text_text_list) == 4u) && (sizeof (jpl_cmd) == 4u) && (sizeof (jpl_text_list) == 4u) && (sizeof (jpl_cmd_list) == 4u) && (sizeof (jpl_pair_text_list_cmd_list_list) == 4u) && (sizeof (jpl_frame) == 4u) && (sizeof (jpl_frame_list) == 4u) && (sizeof (jpl_exp_mode) == 4u) ? 1 : -1)];

/* ── the pools.  Definitions live in the emitted translation unit
   (JPL.md §6: no dynamic allocation); they are declared here so every
   consumer compiles against one capacity.  Index 0 is JPL_NIL and is
   never allocated, so a capacity counts the reserved cell too — and
   since §6.7's ii-b-2b there is one reserved index PER SPACE, because
   each interval is a region in its own right: the array below is not two
   pools, it is one index domain holding a from-space and a to-space that
   move together when jpl_pools_swap() says so. ── */
#define JPL_POOL_SPACES 2u   /* §6.7 paragraph 4: the headroom factor IS a number of
                        intervals — 2 — rather than slack: one space holds the
                        live set and the rest receive the copies a step boundary
                        builds before releasing the original */
extern jpl_nat jpl_pools_space;   /* which interval is current; one writer, jpl_pools_swap() */

#define JPL_POOL_WORD 33286u   /* 2 spaces x (cap + 1) indices: 16642 cells per space
                        each keeping its own reserved 0; from JPL_MAX_WORDS; sh_jpl.v §1's MAX_WORDS, a sum of the already-locked caps: MAX_STACK cells for
    the words a pool-fitting tree holds (§7.1 cmd_fits_words, from cmd_words <= 2*
    cmd_count and cmd_fits), a second MAX_STACK for the runtime-expanded copies an
    FFor/FCase frame holds (the OWED step-machine invariant "one live frame per
    source node" — named in §1, not yet proved), 2*MAX_ENV for the environment's
    name/value cells (§5 benv_words_le), and 2 per-step temporaries. */
#define JPL_WORD_CAP 16642u   /* cells ONE space serves = the artifact's number */
#define JPL_WORD_SPACE (JPL_WORD_CAP + 1u)   /* indices a space occupies */
#define JPL_WORD_LO_BASE 0u
#define JPL_WORD_HI_BASE JPL_WORD_SPACE
#define JPL_WORD_CUR_BASE (jpl_pools_space * JPL_WORD_SPACE)   /* the current interval, read through the
                        space indicator */
#define JPL_WORD_CUR_TOP (JPL_WORD_CUR_BASE + JPL_WORD_SPACE)
#define JPL_WORD_OTHER_BASE (((jpl_pools_space + 1u) % JPL_POOL_SPACES) * JPL_WORD_SPACE)   /* the interval a boundary reads
                        FROM once it has swapped: the swap makes CUR_*
                        the space the copies land in, so the pair still
                        worth naming is the one being abandoned */
#define JPL_WORD_OTHER_TOP (JPL_WORD_OTHER_BASE + JPL_WORD_SPACE)
extern jpl_text jpl_word_pool[JPL_POOL_WORD];
extern jpl_ref jpl_word_origin[JPL_POOL_WORD];   /* §6.7: where a copied cell came from, one
                        entry per INDEX so a handle is the only key;
                        zero is JPL_NIL, i.e. not copied from anywhere
                        (paragraph 4) */
typedef char jpl_check_word_two_regions[((JPL_POOL_WORD == (JPL_POOL_SPACES * JPL_WORD_SPACE)) ? 1 : -1)];
typedef char jpl_check_word_region_serves_the_cap[((JPL_WORD_SPACE - 1u) == JPL_WORD_CAP) ? 1 : -1];
typedef char jpl_check_word_regions_tile_the_array[((JPL_WORD_HI_BASE + JPL_WORD_SPACE) == JPL_POOL_WORD) ? 1 : -1];
typedef char jpl_check_word_origin_is_the_index_domain[((sizeof (jpl_word_origin) == (JPL_POOL_WORD * sizeof (jpl_ref))) ? 1 : -1)];

#define JPL_POOL_PAIR_TEXT_TEXT_LIST 258u   /* 2 spaces x (cap + 1) indices: 128 cells per space
                        each keeping its own reserved 0; from JPL_MAX_ENV; the environment's pair list (sh_jpl.v §5 wf_benv) */
#define JPL_PAIR_TEXT_TEXT_LIST_CAP 128u   /* cells ONE space serves = the artifact's number */
#define JPL_PAIR_TEXT_TEXT_LIST_SPACE (JPL_PAIR_TEXT_TEXT_LIST_CAP + 1u)   /* indices a space occupies */
#define JPL_PAIR_TEXT_TEXT_LIST_LO_BASE 0u
#define JPL_PAIR_TEXT_TEXT_LIST_HI_BASE JPL_PAIR_TEXT_TEXT_LIST_SPACE
#define JPL_PAIR_TEXT_TEXT_LIST_CUR_BASE (jpl_pools_space * JPL_PAIR_TEXT_TEXT_LIST_SPACE)   /* the current interval, read through the
                        space indicator */
#define JPL_PAIR_TEXT_TEXT_LIST_CUR_TOP (JPL_PAIR_TEXT_TEXT_LIST_CUR_BASE + JPL_PAIR_TEXT_TEXT_LIST_SPACE)
#define JPL_PAIR_TEXT_TEXT_LIST_OTHER_BASE (((jpl_pools_space + 1u) % JPL_POOL_SPACES) * JPL_PAIR_TEXT_TEXT_LIST_SPACE)   /* the interval a boundary reads
                        FROM once it has swapped: the swap makes CUR_*
                        the space the copies land in, so the pair still
                        worth naming is the one being abandoned */
#define JPL_PAIR_TEXT_TEXT_LIST_OTHER_TOP (JPL_PAIR_TEXT_TEXT_LIST_OTHER_BASE + JPL_PAIR_TEXT_TEXT_LIST_SPACE)
extern jpl_pair_text_text_list_cell jpl_pair_text_text_list_pool[JPL_POOL_PAIR_TEXT_TEXT_LIST];
extern jpl_ref jpl_pair_text_text_list_origin[JPL_POOL_PAIR_TEXT_TEXT_LIST];   /* §6.7: where a copied cell came from, one
                        entry per INDEX so a handle is the only key;
                        zero is JPL_NIL, i.e. not copied from anywhere
                        (paragraph 4) */
typedef char jpl_check_pair_text_text_list_two_regions[((JPL_POOL_PAIR_TEXT_TEXT_LIST == (JPL_POOL_SPACES * JPL_PAIR_TEXT_TEXT_LIST_SPACE)) ? 1 : -1)];
typedef char jpl_check_pair_text_text_list_region_serves_the_cap[((JPL_PAIR_TEXT_TEXT_LIST_SPACE - 1u) == JPL_PAIR_TEXT_TEXT_LIST_CAP) ? 1 : -1];
typedef char jpl_check_pair_text_text_list_regions_tile_the_array[((JPL_PAIR_TEXT_TEXT_LIST_HI_BASE + JPL_PAIR_TEXT_TEXT_LIST_SPACE) == JPL_POOL_PAIR_TEXT_TEXT_LIST) ? 1 : -1];
typedef char jpl_check_pair_text_text_list_origin_is_the_index_domain[((sizeof (jpl_pair_text_text_list_origin) == (JPL_POOL_PAIR_TEXT_TEXT_LIST * sizeof (jpl_ref))) ? 1 : -1)];

#define JPL_POOL_CMD 8194u   /* 2 spaces x (cap + 1) indices: 4096 cells per space
                        each keeping its own reserved 0; from JPL_MAX_CMD; nodes of one lowered cmd tree (sh_jpl.v §1 MAX_CMD) */
#define JPL_CMD_CAP 4096u   /* cells ONE space serves = the artifact's number */
#define JPL_CMD_SPACE (JPL_CMD_CAP + 1u)   /* indices a space occupies */
#define JPL_CMD_LO_BASE 0u
#define JPL_CMD_HI_BASE JPL_CMD_SPACE
#define JPL_CMD_CUR_BASE (jpl_pools_space * JPL_CMD_SPACE)   /* the current interval, read through the
                        space indicator */
#define JPL_CMD_CUR_TOP (JPL_CMD_CUR_BASE + JPL_CMD_SPACE)
#define JPL_CMD_OTHER_BASE (((jpl_pools_space + 1u) % JPL_POOL_SPACES) * JPL_CMD_SPACE)   /* the interval a boundary reads
                        FROM once it has swapped: the swap makes CUR_*
                        the space the copies land in, so the pair still
                        worth naming is the one being abandoned */
#define JPL_CMD_OTHER_TOP (JPL_CMD_OTHER_BASE + JPL_CMD_SPACE)
extern jpl_cmd_node jpl_cmd_pool[JPL_POOL_CMD];
extern jpl_ref jpl_cmd_origin[JPL_POOL_CMD];   /* §6.7: where a copied cell came from, one
                        entry per INDEX so a handle is the only key;
                        zero is JPL_NIL, i.e. not copied from anywhere
                        (paragraph 4) */
typedef char jpl_check_cmd_two_regions[((JPL_POOL_CMD == (JPL_POOL_SPACES * JPL_CMD_SPACE)) ? 1 : -1)];
typedef char jpl_check_cmd_region_serves_the_cap[((JPL_CMD_SPACE - 1u) == JPL_CMD_CAP) ? 1 : -1];
typedef char jpl_check_cmd_regions_tile_the_array[((JPL_CMD_HI_BASE + JPL_CMD_SPACE) == JPL_POOL_CMD) ? 1 : -1];
typedef char jpl_check_cmd_origin_is_the_index_domain[((sizeof (jpl_cmd_origin) == (JPL_POOL_CMD * sizeof (jpl_ref))) ? 1 : -1)];

#define JPL_POOL_TEXT_LIST 2050u   /* 2 spaces x (cap + 1) indices: 1024 cells per space
                        each keeping its own reserved 0; from JPL_MAX_LIST; an intermediate list (sh_jpl.v §1 MAX_LIST) */
#define JPL_TEXT_LIST_CAP 1024u   /* cells ONE space serves = the artifact's number */
#define JPL_TEXT_LIST_SPACE (JPL_TEXT_LIST_CAP + 1u)   /* indices a space occupies */
#define JPL_TEXT_LIST_LO_BASE 0u
#define JPL_TEXT_LIST_HI_BASE JPL_TEXT_LIST_SPACE
#define JPL_TEXT_LIST_CUR_BASE (jpl_pools_space * JPL_TEXT_LIST_SPACE)   /* the current interval, read through the
                        space indicator */
#define JPL_TEXT_LIST_CUR_TOP (JPL_TEXT_LIST_CUR_BASE + JPL_TEXT_LIST_SPACE)
#define JPL_TEXT_LIST_OTHER_BASE (((jpl_pools_space + 1u) % JPL_POOL_SPACES) * JPL_TEXT_LIST_SPACE)   /* the interval a boundary reads
                        FROM once it has swapped: the swap makes CUR_*
                        the space the copies land in, so the pair still
                        worth naming is the one being abandoned */
#define JPL_TEXT_LIST_OTHER_TOP (JPL_TEXT_LIST_OTHER_BASE + JPL_TEXT_LIST_SPACE)
extern jpl_text_list_cell jpl_text_list_pool[JPL_POOL_TEXT_LIST];
extern jpl_ref jpl_text_list_origin[JPL_POOL_TEXT_LIST];   /* §6.7: where a copied cell came from, one
                        entry per INDEX so a handle is the only key;
                        zero is JPL_NIL, i.e. not copied from anywhere
                        (paragraph 4) */
typedef char jpl_check_text_list_two_regions[((JPL_POOL_TEXT_LIST == (JPL_POOL_SPACES * JPL_TEXT_LIST_SPACE)) ? 1 : -1)];
typedef char jpl_check_text_list_region_serves_the_cap[((JPL_TEXT_LIST_SPACE - 1u) == JPL_TEXT_LIST_CAP) ? 1 : -1];
typedef char jpl_check_text_list_regions_tile_the_array[((JPL_TEXT_LIST_HI_BASE + JPL_TEXT_LIST_SPACE) == JPL_POOL_TEXT_LIST) ? 1 : -1];
typedef char jpl_check_text_list_origin_is_the_index_domain[((sizeof (jpl_text_list_origin) == (JPL_POOL_TEXT_LIST * sizeof (jpl_ref))) ? 1 : -1)];

#define JPL_POOL_CMD_LIST 2050u   /* 2 spaces x (cap + 1) indices: 1024 cells per space
                        each keeping its own reserved 0; from JPL_MAX_LIST; an intermediate list (sh_jpl.v §1 MAX_LIST) */
#define JPL_CMD_LIST_CAP 1024u   /* cells ONE space serves = the artifact's number */
#define JPL_CMD_LIST_SPACE (JPL_CMD_LIST_CAP + 1u)   /* indices a space occupies */
#define JPL_CMD_LIST_LO_BASE 0u
#define JPL_CMD_LIST_HI_BASE JPL_CMD_LIST_SPACE
#define JPL_CMD_LIST_CUR_BASE (jpl_pools_space * JPL_CMD_LIST_SPACE)   /* the current interval, read through the
                        space indicator */
#define JPL_CMD_LIST_CUR_TOP (JPL_CMD_LIST_CUR_BASE + JPL_CMD_LIST_SPACE)
#define JPL_CMD_LIST_OTHER_BASE (((jpl_pools_space + 1u) % JPL_POOL_SPACES) * JPL_CMD_LIST_SPACE)   /* the interval a boundary reads
                        FROM once it has swapped: the swap makes CUR_*
                        the space the copies land in, so the pair still
                        worth naming is the one being abandoned */
#define JPL_CMD_LIST_OTHER_TOP (JPL_CMD_LIST_OTHER_BASE + JPL_CMD_LIST_SPACE)
extern jpl_cmd_list_cell jpl_cmd_list_pool[JPL_POOL_CMD_LIST];
extern jpl_ref jpl_cmd_list_origin[JPL_POOL_CMD_LIST];   /* §6.7: where a copied cell came from, one
                        entry per INDEX so a handle is the only key;
                        zero is JPL_NIL, i.e. not copied from anywhere
                        (paragraph 4) */
typedef char jpl_check_cmd_list_two_regions[((JPL_POOL_CMD_LIST == (JPL_POOL_SPACES * JPL_CMD_LIST_SPACE)) ? 1 : -1)];
typedef char jpl_check_cmd_list_region_serves_the_cap[((JPL_CMD_LIST_SPACE - 1u) == JPL_CMD_LIST_CAP) ? 1 : -1];
typedef char jpl_check_cmd_list_regions_tile_the_array[((JPL_CMD_LIST_HI_BASE + JPL_CMD_LIST_SPACE) == JPL_POOL_CMD_LIST) ? 1 : -1];
typedef char jpl_check_cmd_list_origin_is_the_index_domain[((sizeof (jpl_cmd_list_origin) == (JPL_POOL_CMD_LIST * sizeof (jpl_ref))) ? 1 : -1)];

#define JPL_POOL_PAIR_TEXT_LIST_CMD_LIST_LIST 2050u   /* 2 spaces x (cap + 1) indices: 1024 cells per space
                        each keeping its own reserved 0; from JPL_MAX_LIST; an intermediate list (sh_jpl.v §1 MAX_LIST) */
#define JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_CAP 1024u   /* cells ONE space serves = the artifact's number */
#define JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_SPACE (JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_CAP + 1u)   /* indices a space occupies */
#define JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_LO_BASE 0u
#define JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_HI_BASE JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_SPACE
#define JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_CUR_BASE (jpl_pools_space * JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_SPACE)   /* the current interval, read through the
                        space indicator */
#define JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_CUR_TOP (JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_CUR_BASE + JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_SPACE)
#define JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_OTHER_BASE (((jpl_pools_space + 1u) % JPL_POOL_SPACES) * JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_SPACE)   /* the interval a boundary reads
                        FROM once it has swapped: the swap makes CUR_*
                        the space the copies land in, so the pair still
                        worth naming is the one being abandoned */
#define JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_OTHER_TOP (JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_OTHER_BASE + JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_SPACE)
extern jpl_pair_text_list_cmd_list_list_cell jpl_pair_text_list_cmd_list_list_pool[JPL_POOL_PAIR_TEXT_LIST_CMD_LIST_LIST];
extern jpl_ref jpl_pair_text_list_cmd_list_list_origin[JPL_POOL_PAIR_TEXT_LIST_CMD_LIST_LIST];   /* §6.7: where a copied cell came from, one
                        entry per INDEX so a handle is the only key;
                        zero is JPL_NIL, i.e. not copied from anywhere
                        (paragraph 4) */
typedef char jpl_check_pair_text_list_cmd_list_list_two_regions[((JPL_POOL_PAIR_TEXT_LIST_CMD_LIST_LIST == (JPL_POOL_SPACES * JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_SPACE)) ? 1 : -1)];
typedef char jpl_check_pair_text_list_cmd_list_list_region_serves_the_cap[((JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_SPACE - 1u) == JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_CAP) ? 1 : -1];
typedef char jpl_check_pair_text_list_cmd_list_list_regions_tile_the_array[((JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_HI_BASE + JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_SPACE) == JPL_POOL_PAIR_TEXT_LIST_CMD_LIST_LIST) ? 1 : -1];
typedef char jpl_check_pair_text_list_cmd_list_list_origin_is_the_index_domain[((sizeof (jpl_pair_text_list_cmd_list_list_origin) == (JPL_POOL_PAIR_TEXT_LIST_CMD_LIST_LIST * sizeof (jpl_ref))) ? 1 : -1)];

#define JPL_POOL_FRAME 16386u   /* 2 spaces x (cap + 1) indices: 8192 cells per space
                        each keeping its own reserved 0; from JPL_MAX_STACK; frames of the explicit machine stack (sh_jpl.v §1 MAX_STACK) */
#define JPL_FRAME_CAP 8192u   /* cells ONE space serves = the artifact's number */
#define JPL_FRAME_SPACE (JPL_FRAME_CAP + 1u)   /* indices a space occupies */
#define JPL_FRAME_LO_BASE 0u
#define JPL_FRAME_HI_BASE JPL_FRAME_SPACE
#define JPL_FRAME_CUR_BASE (jpl_pools_space * JPL_FRAME_SPACE)   /* the current interval, read through the
                        space indicator */
#define JPL_FRAME_CUR_TOP (JPL_FRAME_CUR_BASE + JPL_FRAME_SPACE)
#define JPL_FRAME_OTHER_BASE (((jpl_pools_space + 1u) % JPL_POOL_SPACES) * JPL_FRAME_SPACE)   /* the interval a boundary reads
                        FROM once it has swapped: the swap makes CUR_*
                        the space the copies land in, so the pair still
                        worth naming is the one being abandoned */
#define JPL_FRAME_OTHER_TOP (JPL_FRAME_OTHER_BASE + JPL_FRAME_SPACE)
extern jpl_frame_node jpl_frame_pool[JPL_POOL_FRAME];
extern jpl_ref jpl_frame_origin[JPL_POOL_FRAME];   /* §6.7: where a copied cell came from, one
                        entry per INDEX so a handle is the only key;
                        zero is JPL_NIL, i.e. not copied from anywhere
                        (paragraph 4) */
typedef char jpl_check_frame_two_regions[((JPL_POOL_FRAME == (JPL_POOL_SPACES * JPL_FRAME_SPACE)) ? 1 : -1)];
typedef char jpl_check_frame_region_serves_the_cap[((JPL_FRAME_SPACE - 1u) == JPL_FRAME_CAP) ? 1 : -1];
typedef char jpl_check_frame_regions_tile_the_array[((JPL_FRAME_HI_BASE + JPL_FRAME_SPACE) == JPL_POOL_FRAME) ? 1 : -1];
typedef char jpl_check_frame_origin_is_the_index_domain[((sizeof (jpl_frame_origin) == (JPL_POOL_FRAME * sizeof (jpl_ref))) ? 1 : -1)];

#define JPL_POOL_FRAME_LIST 16386u   /* 2 spaces x (cap + 1) indices: 8192 cells per space
                        each keeping its own reserved 0; from JPL_MAX_STACK; the machine stack = frame list */
#define JPL_FRAME_LIST_CAP 8192u   /* cells ONE space serves = the artifact's number */
#define JPL_FRAME_LIST_SPACE (JPL_FRAME_LIST_CAP + 1u)   /* indices a space occupies */
#define JPL_FRAME_LIST_LO_BASE 0u
#define JPL_FRAME_LIST_HI_BASE JPL_FRAME_LIST_SPACE
#define JPL_FRAME_LIST_CUR_BASE (jpl_pools_space * JPL_FRAME_LIST_SPACE)   /* the current interval, read through the
                        space indicator */
#define JPL_FRAME_LIST_CUR_TOP (JPL_FRAME_LIST_CUR_BASE + JPL_FRAME_LIST_SPACE)
#define JPL_FRAME_LIST_OTHER_BASE (((jpl_pools_space + 1u) % JPL_POOL_SPACES) * JPL_FRAME_LIST_SPACE)   /* the interval a boundary reads
                        FROM once it has swapped: the swap makes CUR_*
                        the space the copies land in, so the pair still
                        worth naming is the one being abandoned */
#define JPL_FRAME_LIST_OTHER_TOP (JPL_FRAME_LIST_OTHER_BASE + JPL_FRAME_LIST_SPACE)
extern jpl_frame_list_cell jpl_frame_list_pool[JPL_POOL_FRAME_LIST];
extern jpl_ref jpl_frame_list_origin[JPL_POOL_FRAME_LIST];   /* §6.7: where a copied cell came from, one
                        entry per INDEX so a handle is the only key;
                        zero is JPL_NIL, i.e. not copied from anywhere
                        (paragraph 4) */
typedef char jpl_check_frame_list_two_regions[((JPL_POOL_FRAME_LIST == (JPL_POOL_SPACES * JPL_FRAME_LIST_SPACE)) ? 1 : -1)];
typedef char jpl_check_frame_list_region_serves_the_cap[((JPL_FRAME_LIST_SPACE - 1u) == JPL_FRAME_LIST_CAP) ? 1 : -1];
typedef char jpl_check_frame_list_regions_tile_the_array[((JPL_FRAME_LIST_HI_BASE + JPL_FRAME_LIST_SPACE) == JPL_POOL_FRAME_LIST) ? 1 : -1];
typedef char jpl_check_frame_list_origin_is_the_index_domain[((sizeof (jpl_frame_list_origin) == (JPL_POOL_FRAME_LIST * sizeof (jpl_ref))) ? 1 : -1)];

/* ── the pool runtime (JPL.md §6.6, 5-B.3b-ii-b-1; two intervals since
   5-B.3b-ii-b-2b, §6.7 paragraph 4): one bounded region per SPACE per pool
   above.  Declarations only — the definitions and bodies are in the generated
   translation unit sh_run_jpl_pools.c, which includes this header, and that
   file is the only C in this tree holding a mutable static.  Each interval
   reserves its own index 0 as JPL_NIL, so a space of CAP + 1 indices serves
   CAP cells and the array's C = 2 * (CAP + 1) indices serve 2 * CAP.  Index 0
   and index CAP + 1 are the two reserved slots and belong to no cell (§6.7).
   Reclamation is at region granularity because a per-cell free needs the
   reachability rule §6.5's ii-b-2 owns before it is safe, not a function; a
   reset does NOT clear cells, since clearing them at every step boundary would
   price the step by the pool rather than by the data and no lemma requires the
   bytes to be zero — the same argument covers `origin`, whose stale entries sit
   in the interval that becomes the to-space and are written before any scan
   reads them.  is_live is the guard rail that makes a handle carried across a
   reset or a swap observable: a comparison against the current interval, not a
   liveness analysis.  The SCAN POINTER is here since ii-b-2c (§6.7 paragraph
   5bis), and so is everything it reads: one word accessor pair, one evac, one
   queue start, one scan step, one drain per pool, plus the counters that make
   the copy measured rather than described.  Every one of them has a writer in
   the generated translation unit below — §6.2's rule against a counter nothing
   writes is why the badtag counter appears only under a pool whose cell has a
   tag to get wrong. */
#define JPL_REF_TOP 4294967295u   /* counters saturate here, never wrap (§4.2) */
typedef char jpl_check_ref_top_is_the_handle_word[((sizeof (jpl_ref) == 4u) ? 1 : -1)];

/* word: jpl_word_pool of JPL_POOL_WORD indices x 2 spaces, 16642 cells per space, handled as jpl_wref
   (JPL.md §6.7 paragraph 4).  Which space is current is ONE global for the
   whole runtime, not one flag per pool: the graph moves together at a step
   boundary, so per-pool indicators would be several chances to disagree about
   a fact that has one cause. */
extern jpl_ref jpl_word_next;     /* an ABSOLUTE index into JPL_POOL_WORD, always inside the current
                                    interval: the lowest index not yet handed out, so
                                    CUR_BASE + 1u is an empty region */
extern jpl_ref jpl_word_peak;     /* the most cells ANY ONE region served — a count, not
                                    the high-water index of one big array (decision 4's
                                    quantity is cells) */
extern jpl_ref jpl_word_taken;    /* cells served since the program started */
extern jpl_ref jpl_word_refused;  /* allocations that found no cell: §6.6's saturate-to-error edge */
extern jpl_ref jpl_word_scan;     /* the to interval's second pointer: the lowest index
                                    whose cells edges have not been rewritten.  It is a
                                    counter only in the sense that `next` is one —
                                    §6.7 paragraph 5bis's drain is what reads it, and it
                                    starts where reset rewinds next to, so an empty queue
                                    and an empty region are the same index */
extern jpl_ref jpl_word_copied;   /* cells evacuated into the to interval, cumulative like
                                    taken: a boundary's copy count is its delta (§6.7) */
extern jpl_ref jpl_word_forwarded; /* references answered by an existing copy rather than
                                    a second cell — the sharing the forwarding pointer
                                    exists to buy, measured instead of claimed */
extern jpl_ref jpl_word_badref;   /* evac called on a handle outside the interval it reads
                                    from: a copy of a copy, a reserved base, an index past
                                    the array.  5bis's refuse-and-count edge, one per pool
                                    because which pool was asked is the readable fact */
typedef char jpl_check_word_capacity_fits_the_counter[((JPL_POOL_WORD < JPL_REF_TOP) ? 1 : -1)];
jpl_wref jpl_word_alloc(void);   /* JPL_NIL once the CURRENT interval of 16642 cells is full */
jpl_ref jpl_word_reset(void);   /* cells returned; next rewinds to the CURRENT interval's own base + 1u */
jpl_bool jpl_word_is_live(jpl_ref h);   /* h in the current interval and below next: after
   a swap a handle from the other interval reads dead WHILE SITTING BELOW
   next, which is the case §6.6's `h < next` could not distinguish and
   §6.7's aliasing debt named */
jpl_ref jpl_word_word_at(jpl_ref h, jpl_ref i);   /* one WORD of jpl_text, in the struct's own
                                    field order: i is a position, not a byte, and an
                                    index past the cell answers JPL_NIL (§6.7 paragraph
                                    5bis).  The chain is derived from the members the
                                    layout rule that emitted jpl_text registered, so it cannot
                                    describe a cell other than the one word_edge classes */
void jpl_word_word_put(jpl_ref h, jpl_ref i, jpl_ref v);   /* the scan's one write, over the
                                    same arms as jpl_word_word_at: no cell in this tree is
                                    written through an address */
jpl_ref jpl_word_evac(jpl_ref h);   /* copy jpl_text's cell h into the current interval and
                                    return the copy, or forward to the copy already made
                                    (§6.7 paragraph 5bis: the four-arm test on word_origin,
                                    one C99 structure assignment, and alloc clearing the
                                    origin of every cell it hands out) */
void jpl_word_queue_start(void);   /* scan = CUR_BASE + 1u, the same expression
                                    reset uses, after evac has copied the
                                    roots that make the queue non-empty */
void jpl_word_scan_one(void);   /* rewrite word's EDGE words at scan and advance
                                    scan by one cell */
void jpl_word_drain(void);   /* scan_one until scan reaches next: a fixpoint
                                    over word's to region, bounded by the
                                    interval (R3) and not recursive (R4) */

/* pair_text_text_list: jpl_pair_text_text_list_pool of JPL_POOL_PAIR_TEXT_TEXT_LIST indices x 2 spaces, 128 cells per space, handled as jpl_pair_text_text_list
   (JPL.md §6.7 paragraph 4).  Which space is current is ONE global for the
   whole runtime, not one flag per pool: the graph moves together at a step
   boundary, so per-pool indicators would be several chances to disagree about
   a fact that has one cause. */
extern jpl_ref jpl_pair_text_text_list_next;     /* an ABSOLUTE index into JPL_POOL_PAIR_TEXT_TEXT_LIST, always inside the current
                                    interval: the lowest index not yet handed out, so
                                    CUR_BASE + 1u is an empty region */
extern jpl_ref jpl_pair_text_text_list_peak;     /* the most cells ANY ONE region served — a count, not
                                    the high-water index of one big array (decision 4's
                                    quantity is cells) */
extern jpl_ref jpl_pair_text_text_list_taken;    /* cells served since the program started */
extern jpl_ref jpl_pair_text_text_list_refused;  /* allocations that found no cell: §6.6's saturate-to-error edge */
extern jpl_ref jpl_pair_text_text_list_scan;     /* the to interval's second pointer: the lowest index
                                    whose cells edges have not been rewritten.  It is a
                                    counter only in the sense that `next` is one —
                                    §6.7 paragraph 5bis's drain is what reads it, and it
                                    starts where reset rewinds next to, so an empty queue
                                    and an empty region are the same index */
extern jpl_ref jpl_pair_text_text_list_copied;   /* cells evacuated into the to interval, cumulative like
                                    taken: a boundary's copy count is its delta (§6.7) */
extern jpl_ref jpl_pair_text_text_list_forwarded; /* references answered by an existing copy rather than
                                    a second cell — the sharing the forwarding pointer
                                    exists to buy, measured instead of claimed */
extern jpl_ref jpl_pair_text_text_list_badref;   /* evac called on a handle outside the interval it reads
                                    from: a copy of a copy, a reserved base, an index past
                                    the array.  5bis's refuse-and-count edge, one per pool
                                    because which pool was asked is the readable fact */
typedef char jpl_check_pair_text_text_list_capacity_fits_the_counter[((JPL_POOL_PAIR_TEXT_TEXT_LIST < JPL_REF_TOP) ? 1 : -1)];
jpl_pair_text_text_list jpl_pair_text_text_list_alloc(void);   /* JPL_NIL once the CURRENT interval of 128 cells is full */
jpl_ref jpl_pair_text_text_list_reset(void);   /* cells returned; next rewinds to the CURRENT interval's own base + 1u */
jpl_bool jpl_pair_text_text_list_is_live(jpl_ref h);   /* h in the current interval and below next: after
   a swap a handle from the other interval reads dead WHILE SITTING BELOW
   next, which is the case §6.6's `h < next` could not distinguish and
   §6.7's aliasing debt named */
jpl_ref jpl_pair_text_text_list_word_at(jpl_ref h, jpl_ref i);   /* one WORD of jpl_pair_text_text_list_cell, in the struct's own
                                    field order: i is a position, not a byte, and an
                                    index past the cell answers JPL_NIL (§6.7 paragraph
                                    5bis).  The chain is derived from the members the
                                    layout rule that emitted jpl_pair_text_text_list_cell registered, so it cannot
                                    describe a cell other than the one pair_text_text_list_edge classes */
void jpl_pair_text_text_list_word_put(jpl_ref h, jpl_ref i, jpl_ref v);   /* the scan's one write, over the
                                    same arms as jpl_pair_text_text_list_word_at: no cell in this tree is
                                    written through an address */
jpl_ref jpl_pair_text_text_list_evac(jpl_ref h);   /* copy jpl_pair_text_text_list_cell's cell h into the current interval and
                                    return the copy, or forward to the copy already made
                                    (§6.7 paragraph 5bis: the four-arm test on pair_text_text_list_origin,
                                    one C99 structure assignment, and alloc clearing the
                                    origin of every cell it hands out) */
void jpl_pair_text_text_list_queue_start(void);   /* scan = CUR_BASE + 1u, the same expression
                                    reset uses, after evac has copied the
                                    roots that make the queue non-empty */
void jpl_pair_text_text_list_scan_one(void);   /* rewrite pair_text_text_list's EDGE words at scan and advance
                                    scan by one cell */
void jpl_pair_text_text_list_drain(void);   /* scan_one until scan reaches next: a fixpoint
                                    over pair_text_text_list's to region, bounded by the
                                    interval (R3) and not recursive (R4) */

/* cmd: jpl_cmd_pool of JPL_POOL_CMD indices x 2 spaces, 4096 cells per space, handled as jpl_cmd
   (JPL.md §6.7 paragraph 4).  Which space is current is ONE global for the
   whole runtime, not one flag per pool: the graph moves together at a step
   boundary, so per-pool indicators would be several chances to disagree about
   a fact that has one cause. */
extern jpl_ref jpl_cmd_next;     /* an ABSOLUTE index into JPL_POOL_CMD, always inside the current
                                    interval: the lowest index not yet handed out, so
                                    CUR_BASE + 1u is an empty region */
extern jpl_ref jpl_cmd_peak;     /* the most cells ANY ONE region served — a count, not
                                    the high-water index of one big array (decision 4's
                                    quantity is cells) */
extern jpl_ref jpl_cmd_taken;    /* cells served since the program started */
extern jpl_ref jpl_cmd_refused;  /* allocations that found no cell: §6.6's saturate-to-error edge */
extern jpl_ref jpl_cmd_scan;     /* the to interval's second pointer: the lowest index
                                    whose cells edges have not been rewritten.  It is a
                                    counter only in the sense that `next` is one —
                                    §6.7 paragraph 5bis's drain is what reads it, and it
                                    starts where reset rewinds next to, so an empty queue
                                    and an empty region are the same index */
extern jpl_ref jpl_cmd_copied;   /* cells evacuated into the to interval, cumulative like
                                    taken: a boundary's copy count is its delta (§6.7) */
extern jpl_ref jpl_cmd_forwarded; /* references answered by an existing copy rather than
                                    a second cell — the sharing the forwarding pointer
                                    exists to buy, measured instead of claimed */
extern jpl_ref jpl_cmd_badref;   /* evac called on a handle outside the interval it reads
                                    from: a copy of a copy, a reserved base, an index past
                                    the array.  5bis's refuse-and-count edge, one per pool
                                    because which pool was asked is the readable fact */
extern jpl_ref jpl_cmd_badtag; /* a tag word with no row in cmd_edge: the scan stops on
                                    that cell rather than walking its slots as scalars
                                    (§6.7 paragraph 5bis).  Emitted only for a tagged
                                    pool — an untagged cell has no tag to be wrong, and
                                    §6.2 refuses a counter nothing writes */
typedef char jpl_check_cmd_capacity_fits_the_counter[((JPL_POOL_CMD < JPL_REF_TOP) ? 1 : -1)];
jpl_cmd jpl_cmd_alloc(void);   /* JPL_NIL once the CURRENT interval of 4096 cells is full */
jpl_ref jpl_cmd_reset(void);   /* cells returned; next rewinds to the CURRENT interval's own base + 1u */
jpl_bool jpl_cmd_is_live(jpl_ref h);   /* h in the current interval and below next: after
   a swap a handle from the other interval reads dead WHILE SITTING BELOW
   next, which is the case §6.6's `h < next` could not distinguish and
   §6.7's aliasing debt named */
jpl_ref jpl_cmd_word_at(jpl_ref h, jpl_ref i);   /* one WORD of jpl_cmd_node, in the struct's own
                                    field order: i is a position, not a byte, and an
                                    index past the cell answers JPL_NIL (§6.7 paragraph
                                    5bis).  The chain is derived from the members the
                                    layout rule that emitted jpl_cmd_node registered, so it cannot
                                    describe a cell other than the one cmd_edge classes */
void jpl_cmd_word_put(jpl_ref h, jpl_ref i, jpl_ref v);   /* the scan's one write, over the
                                    same arms as jpl_cmd_word_at: no cell in this tree is
                                    written through an address */
jpl_ref jpl_cmd_evac(jpl_ref h);   /* copy jpl_cmd_node's cell h into the current interval and
                                    return the copy, or forward to the copy already made
                                    (§6.7 paragraph 5bis: the four-arm test on cmd_origin,
                                    one C99 structure assignment, and alloc clearing the
                                    origin of every cell it hands out) */
void jpl_cmd_queue_start(void);   /* scan = CUR_BASE + 1u, the same expression
                                    reset uses, after evac has copied the
                                    roots that make the queue non-empty */
void jpl_cmd_scan_one(void);   /* rewrite cmd's EDGE words at scan and advance
                                    scan by one cell */
void jpl_cmd_drain(void);   /* scan_one until scan reaches next: a fixpoint
                                    over cmd's to region, bounded by the
                                    interval (R3) and not recursive (R4) */

/* text_list: jpl_text_list_pool of JPL_POOL_TEXT_LIST indices x 2 spaces, 1024 cells per space, handled as jpl_text_list
   (JPL.md §6.7 paragraph 4).  Which space is current is ONE global for the
   whole runtime, not one flag per pool: the graph moves together at a step
   boundary, so per-pool indicators would be several chances to disagree about
   a fact that has one cause. */
extern jpl_ref jpl_text_list_next;     /* an ABSOLUTE index into JPL_POOL_TEXT_LIST, always inside the current
                                    interval: the lowest index not yet handed out, so
                                    CUR_BASE + 1u is an empty region */
extern jpl_ref jpl_text_list_peak;     /* the most cells ANY ONE region served — a count, not
                                    the high-water index of one big array (decision 4's
                                    quantity is cells) */
extern jpl_ref jpl_text_list_taken;    /* cells served since the program started */
extern jpl_ref jpl_text_list_refused;  /* allocations that found no cell: §6.6's saturate-to-error edge */
extern jpl_ref jpl_text_list_scan;     /* the to interval's second pointer: the lowest index
                                    whose cells edges have not been rewritten.  It is a
                                    counter only in the sense that `next` is one —
                                    §6.7 paragraph 5bis's drain is what reads it, and it
                                    starts where reset rewinds next to, so an empty queue
                                    and an empty region are the same index */
extern jpl_ref jpl_text_list_copied;   /* cells evacuated into the to interval, cumulative like
                                    taken: a boundary's copy count is its delta (§6.7) */
extern jpl_ref jpl_text_list_forwarded; /* references answered by an existing copy rather than
                                    a second cell — the sharing the forwarding pointer
                                    exists to buy, measured instead of claimed */
extern jpl_ref jpl_text_list_badref;   /* evac called on a handle outside the interval it reads
                                    from: a copy of a copy, a reserved base, an index past
                                    the array.  5bis's refuse-and-count edge, one per pool
                                    because which pool was asked is the readable fact */
typedef char jpl_check_text_list_capacity_fits_the_counter[((JPL_POOL_TEXT_LIST < JPL_REF_TOP) ? 1 : -1)];
jpl_text_list jpl_text_list_alloc(void);   /* JPL_NIL once the CURRENT interval of 1024 cells is full */
jpl_ref jpl_text_list_reset(void);   /* cells returned; next rewinds to the CURRENT interval's own base + 1u */
jpl_bool jpl_text_list_is_live(jpl_ref h);   /* h in the current interval and below next: after
   a swap a handle from the other interval reads dead WHILE SITTING BELOW
   next, which is the case §6.6's `h < next` could not distinguish and
   §6.7's aliasing debt named */
jpl_ref jpl_text_list_word_at(jpl_ref h, jpl_ref i);   /* one WORD of jpl_text_list_cell, in the struct's own
                                    field order: i is a position, not a byte, and an
                                    index past the cell answers JPL_NIL (§6.7 paragraph
                                    5bis).  The chain is derived from the members the
                                    layout rule that emitted jpl_text_list_cell registered, so it cannot
                                    describe a cell other than the one text_list_edge classes */
void jpl_text_list_word_put(jpl_ref h, jpl_ref i, jpl_ref v);   /* the scan's one write, over the
                                    same arms as jpl_text_list_word_at: no cell in this tree is
                                    written through an address */
jpl_ref jpl_text_list_evac(jpl_ref h);   /* copy jpl_text_list_cell's cell h into the current interval and
                                    return the copy, or forward to the copy already made
                                    (§6.7 paragraph 5bis: the four-arm test on text_list_origin,
                                    one C99 structure assignment, and alloc clearing the
                                    origin of every cell it hands out) */
void jpl_text_list_queue_start(void);   /* scan = CUR_BASE + 1u, the same expression
                                    reset uses, after evac has copied the
                                    roots that make the queue non-empty */
void jpl_text_list_scan_one(void);   /* rewrite text_list's EDGE words at scan and advance
                                    scan by one cell */
void jpl_text_list_drain(void);   /* scan_one until scan reaches next: a fixpoint
                                    over text_list's to region, bounded by the
                                    interval (R3) and not recursive (R4) */

/* cmd_list: jpl_cmd_list_pool of JPL_POOL_CMD_LIST indices x 2 spaces, 1024 cells per space, handled as jpl_cmd_list
   (JPL.md §6.7 paragraph 4).  Which space is current is ONE global for the
   whole runtime, not one flag per pool: the graph moves together at a step
   boundary, so per-pool indicators would be several chances to disagree about
   a fact that has one cause. */
extern jpl_ref jpl_cmd_list_next;     /* an ABSOLUTE index into JPL_POOL_CMD_LIST, always inside the current
                                    interval: the lowest index not yet handed out, so
                                    CUR_BASE + 1u is an empty region */
extern jpl_ref jpl_cmd_list_peak;     /* the most cells ANY ONE region served — a count, not
                                    the high-water index of one big array (decision 4's
                                    quantity is cells) */
extern jpl_ref jpl_cmd_list_taken;    /* cells served since the program started */
extern jpl_ref jpl_cmd_list_refused;  /* allocations that found no cell: §6.6's saturate-to-error edge */
extern jpl_ref jpl_cmd_list_scan;     /* the to interval's second pointer: the lowest index
                                    whose cells edges have not been rewritten.  It is a
                                    counter only in the sense that `next` is one —
                                    §6.7 paragraph 5bis's drain is what reads it, and it
                                    starts where reset rewinds next to, so an empty queue
                                    and an empty region are the same index */
extern jpl_ref jpl_cmd_list_copied;   /* cells evacuated into the to interval, cumulative like
                                    taken: a boundary's copy count is its delta (§6.7) */
extern jpl_ref jpl_cmd_list_forwarded; /* references answered by an existing copy rather than
                                    a second cell — the sharing the forwarding pointer
                                    exists to buy, measured instead of claimed */
extern jpl_ref jpl_cmd_list_badref;   /* evac called on a handle outside the interval it reads
                                    from: a copy of a copy, a reserved base, an index past
                                    the array.  5bis's refuse-and-count edge, one per pool
                                    because which pool was asked is the readable fact */
typedef char jpl_check_cmd_list_capacity_fits_the_counter[((JPL_POOL_CMD_LIST < JPL_REF_TOP) ? 1 : -1)];
jpl_cmd_list jpl_cmd_list_alloc(void);   /* JPL_NIL once the CURRENT interval of 1024 cells is full */
jpl_ref jpl_cmd_list_reset(void);   /* cells returned; next rewinds to the CURRENT interval's own base + 1u */
jpl_bool jpl_cmd_list_is_live(jpl_ref h);   /* h in the current interval and below next: after
   a swap a handle from the other interval reads dead WHILE SITTING BELOW
   next, which is the case §6.6's `h < next` could not distinguish and
   §6.7's aliasing debt named */
jpl_ref jpl_cmd_list_word_at(jpl_ref h, jpl_ref i);   /* one WORD of jpl_cmd_list_cell, in the struct's own
                                    field order: i is a position, not a byte, and an
                                    index past the cell answers JPL_NIL (§6.7 paragraph
                                    5bis).  The chain is derived from the members the
                                    layout rule that emitted jpl_cmd_list_cell registered, so it cannot
                                    describe a cell other than the one cmd_list_edge classes */
void jpl_cmd_list_word_put(jpl_ref h, jpl_ref i, jpl_ref v);   /* the scan's one write, over the
                                    same arms as jpl_cmd_list_word_at: no cell in this tree is
                                    written through an address */
jpl_ref jpl_cmd_list_evac(jpl_ref h);   /* copy jpl_cmd_list_cell's cell h into the current interval and
                                    return the copy, or forward to the copy already made
                                    (§6.7 paragraph 5bis: the four-arm test on cmd_list_origin,
                                    one C99 structure assignment, and alloc clearing the
                                    origin of every cell it hands out) */
void jpl_cmd_list_queue_start(void);   /* scan = CUR_BASE + 1u, the same expression
                                    reset uses, after evac has copied the
                                    roots that make the queue non-empty */
void jpl_cmd_list_scan_one(void);   /* rewrite cmd_list's EDGE words at scan and advance
                                    scan by one cell */
void jpl_cmd_list_drain(void);   /* scan_one until scan reaches next: a fixpoint
                                    over cmd_list's to region, bounded by the
                                    interval (R3) and not recursive (R4) */

/* pair_text_list_cmd_list_list: jpl_pair_text_list_cmd_list_list_pool of JPL_POOL_PAIR_TEXT_LIST_CMD_LIST_LIST indices x 2 spaces, 1024 cells per space, handled as jpl_pair_text_list_cmd_list_list
   (JPL.md §6.7 paragraph 4).  Which space is current is ONE global for the
   whole runtime, not one flag per pool: the graph moves together at a step
   boundary, so per-pool indicators would be several chances to disagree about
   a fact that has one cause. */
extern jpl_ref jpl_pair_text_list_cmd_list_list_next;     /* an ABSOLUTE index into JPL_POOL_PAIR_TEXT_LIST_CMD_LIST_LIST, always inside the current
                                    interval: the lowest index not yet handed out, so
                                    CUR_BASE + 1u is an empty region */
extern jpl_ref jpl_pair_text_list_cmd_list_list_peak;     /* the most cells ANY ONE region served — a count, not
                                    the high-water index of one big array (decision 4's
                                    quantity is cells) */
extern jpl_ref jpl_pair_text_list_cmd_list_list_taken;    /* cells served since the program started */
extern jpl_ref jpl_pair_text_list_cmd_list_list_refused;  /* allocations that found no cell: §6.6's saturate-to-error edge */
extern jpl_ref jpl_pair_text_list_cmd_list_list_scan;     /* the to interval's second pointer: the lowest index
                                    whose cells edges have not been rewritten.  It is a
                                    counter only in the sense that `next` is one —
                                    §6.7 paragraph 5bis's drain is what reads it, and it
                                    starts where reset rewinds next to, so an empty queue
                                    and an empty region are the same index */
extern jpl_ref jpl_pair_text_list_cmd_list_list_copied;   /* cells evacuated into the to interval, cumulative like
                                    taken: a boundary's copy count is its delta (§6.7) */
extern jpl_ref jpl_pair_text_list_cmd_list_list_forwarded; /* references answered by an existing copy rather than
                                    a second cell — the sharing the forwarding pointer
                                    exists to buy, measured instead of claimed */
extern jpl_ref jpl_pair_text_list_cmd_list_list_badref;   /* evac called on a handle outside the interval it reads
                                    from: a copy of a copy, a reserved base, an index past
                                    the array.  5bis's refuse-and-count edge, one per pool
                                    because which pool was asked is the readable fact */
typedef char jpl_check_pair_text_list_cmd_list_list_capacity_fits_the_counter[((JPL_POOL_PAIR_TEXT_LIST_CMD_LIST_LIST < JPL_REF_TOP) ? 1 : -1)];
jpl_pair_text_list_cmd_list_list jpl_pair_text_list_cmd_list_list_alloc(void);   /* JPL_NIL once the CURRENT interval of 1024 cells is full */
jpl_ref jpl_pair_text_list_cmd_list_list_reset(void);   /* cells returned; next rewinds to the CURRENT interval's own base + 1u */
jpl_bool jpl_pair_text_list_cmd_list_list_is_live(jpl_ref h);   /* h in the current interval and below next: after
   a swap a handle from the other interval reads dead WHILE SITTING BELOW
   next, which is the case §6.6's `h < next` could not distinguish and
   §6.7's aliasing debt named */
jpl_ref jpl_pair_text_list_cmd_list_list_word_at(jpl_ref h, jpl_ref i);   /* one WORD of jpl_pair_text_list_cmd_list_list_cell, in the struct's own
                                    field order: i is a position, not a byte, and an
                                    index past the cell answers JPL_NIL (§6.7 paragraph
                                    5bis).  The chain is derived from the members the
                                    layout rule that emitted jpl_pair_text_list_cmd_list_list_cell registered, so it cannot
                                    describe a cell other than the one pair_text_list_cmd_list_list_edge classes */
void jpl_pair_text_list_cmd_list_list_word_put(jpl_ref h, jpl_ref i, jpl_ref v);   /* the scan's one write, over the
                                    same arms as jpl_pair_text_list_cmd_list_list_word_at: no cell in this tree is
                                    written through an address */
jpl_ref jpl_pair_text_list_cmd_list_list_evac(jpl_ref h);   /* copy jpl_pair_text_list_cmd_list_list_cell's cell h into the current interval and
                                    return the copy, or forward to the copy already made
                                    (§6.7 paragraph 5bis: the four-arm test on pair_text_list_cmd_list_list_origin,
                                    one C99 structure assignment, and alloc clearing the
                                    origin of every cell it hands out) */
void jpl_pair_text_list_cmd_list_list_queue_start(void);   /* scan = CUR_BASE + 1u, the same expression
                                    reset uses, after evac has copied the
                                    roots that make the queue non-empty */
void jpl_pair_text_list_cmd_list_list_scan_one(void);   /* rewrite pair_text_list_cmd_list_list's EDGE words at scan and advance
                                    scan by one cell */
void jpl_pair_text_list_cmd_list_list_drain(void);   /* scan_one until scan reaches next: a fixpoint
                                    over pair_text_list_cmd_list_list's to region, bounded by the
                                    interval (R3) and not recursive (R4) */

/* frame: jpl_frame_pool of JPL_POOL_FRAME indices x 2 spaces, 8192 cells per space, handled as jpl_frame
   (JPL.md §6.7 paragraph 4).  Which space is current is ONE global for the
   whole runtime, not one flag per pool: the graph moves together at a step
   boundary, so per-pool indicators would be several chances to disagree about
   a fact that has one cause. */
extern jpl_ref jpl_frame_next;     /* an ABSOLUTE index into JPL_POOL_FRAME, always inside the current
                                    interval: the lowest index not yet handed out, so
                                    CUR_BASE + 1u is an empty region */
extern jpl_ref jpl_frame_peak;     /* the most cells ANY ONE region served — a count, not
                                    the high-water index of one big array (decision 4's
                                    quantity is cells) */
extern jpl_ref jpl_frame_taken;    /* cells served since the program started */
extern jpl_ref jpl_frame_refused;  /* allocations that found no cell: §6.6's saturate-to-error edge */
extern jpl_ref jpl_frame_scan;     /* the to interval's second pointer: the lowest index
                                    whose cells edges have not been rewritten.  It is a
                                    counter only in the sense that `next` is one —
                                    §6.7 paragraph 5bis's drain is what reads it, and it
                                    starts where reset rewinds next to, so an empty queue
                                    and an empty region are the same index */
extern jpl_ref jpl_frame_copied;   /* cells evacuated into the to interval, cumulative like
                                    taken: a boundary's copy count is its delta (§6.7) */
extern jpl_ref jpl_frame_forwarded; /* references answered by an existing copy rather than
                                    a second cell — the sharing the forwarding pointer
                                    exists to buy, measured instead of claimed */
extern jpl_ref jpl_frame_badref;   /* evac called on a handle outside the interval it reads
                                    from: a copy of a copy, a reserved base, an index past
                                    the array.  5bis's refuse-and-count edge, one per pool
                                    because which pool was asked is the readable fact */
extern jpl_ref jpl_frame_badtag; /* a tag word with no row in frame_edge: the scan stops on
                                    that cell rather than walking its slots as scalars
                                    (§6.7 paragraph 5bis).  Emitted only for a tagged
                                    pool — an untagged cell has no tag to be wrong, and
                                    §6.2 refuses a counter nothing writes */
typedef char jpl_check_frame_capacity_fits_the_counter[((JPL_POOL_FRAME < JPL_REF_TOP) ? 1 : -1)];
jpl_frame jpl_frame_alloc(void);   /* JPL_NIL once the CURRENT interval of 8192 cells is full */
jpl_ref jpl_frame_reset(void);   /* cells returned; next rewinds to the CURRENT interval's own base + 1u */
jpl_bool jpl_frame_is_live(jpl_ref h);   /* h in the current interval and below next: after
   a swap a handle from the other interval reads dead WHILE SITTING BELOW
   next, which is the case §6.6's `h < next` could not distinguish and
   §6.7's aliasing debt named */
jpl_ref jpl_frame_word_at(jpl_ref h, jpl_ref i);   /* one WORD of jpl_frame_node, in the struct's own
                                    field order: i is a position, not a byte, and an
                                    index past the cell answers JPL_NIL (§6.7 paragraph
                                    5bis).  The chain is derived from the members the
                                    layout rule that emitted jpl_frame_node registered, so it cannot
                                    describe a cell other than the one frame_edge classes */
void jpl_frame_word_put(jpl_ref h, jpl_ref i, jpl_ref v);   /* the scan's one write, over the
                                    same arms as jpl_frame_word_at: no cell in this tree is
                                    written through an address */
jpl_ref jpl_frame_evac(jpl_ref h);   /* copy jpl_frame_node's cell h into the current interval and
                                    return the copy, or forward to the copy already made
                                    (§6.7 paragraph 5bis: the four-arm test on frame_origin,
                                    one C99 structure assignment, and alloc clearing the
                                    origin of every cell it hands out) */
void jpl_frame_queue_start(void);   /* scan = CUR_BASE + 1u, the same expression
                                    reset uses, after evac has copied the
                                    roots that make the queue non-empty */
void jpl_frame_scan_one(void);   /* rewrite frame's EDGE words at scan and advance
                                    scan by one cell */
void jpl_frame_drain(void);   /* scan_one until scan reaches next: a fixpoint
                                    over frame's to region, bounded by the
                                    interval (R3) and not recursive (R4) */

/* frame_list: jpl_frame_list_pool of JPL_POOL_FRAME_LIST indices x 2 spaces, 8192 cells per space, handled as jpl_frame_list
   (JPL.md §6.7 paragraph 4).  Which space is current is ONE global for the
   whole runtime, not one flag per pool: the graph moves together at a step
   boundary, so per-pool indicators would be several chances to disagree about
   a fact that has one cause. */
extern jpl_ref jpl_frame_list_next;     /* an ABSOLUTE index into JPL_POOL_FRAME_LIST, always inside the current
                                    interval: the lowest index not yet handed out, so
                                    CUR_BASE + 1u is an empty region */
extern jpl_ref jpl_frame_list_peak;     /* the most cells ANY ONE region served — a count, not
                                    the high-water index of one big array (decision 4's
                                    quantity is cells) */
extern jpl_ref jpl_frame_list_taken;    /* cells served since the program started */
extern jpl_ref jpl_frame_list_refused;  /* allocations that found no cell: §6.6's saturate-to-error edge */
extern jpl_ref jpl_frame_list_scan;     /* the to interval's second pointer: the lowest index
                                    whose cells edges have not been rewritten.  It is a
                                    counter only in the sense that `next` is one —
                                    §6.7 paragraph 5bis's drain is what reads it, and it
                                    starts where reset rewinds next to, so an empty queue
                                    and an empty region are the same index */
extern jpl_ref jpl_frame_list_copied;   /* cells evacuated into the to interval, cumulative like
                                    taken: a boundary's copy count is its delta (§6.7) */
extern jpl_ref jpl_frame_list_forwarded; /* references answered by an existing copy rather than
                                    a second cell — the sharing the forwarding pointer
                                    exists to buy, measured instead of claimed */
extern jpl_ref jpl_frame_list_badref;   /* evac called on a handle outside the interval it reads
                                    from: a copy of a copy, a reserved base, an index past
                                    the array.  5bis's refuse-and-count edge, one per pool
                                    because which pool was asked is the readable fact */
typedef char jpl_check_frame_list_capacity_fits_the_counter[((JPL_POOL_FRAME_LIST < JPL_REF_TOP) ? 1 : -1)];
jpl_frame_list jpl_frame_list_alloc(void);   /* JPL_NIL once the CURRENT interval of 8192 cells is full */
jpl_ref jpl_frame_list_reset(void);   /* cells returned; next rewinds to the CURRENT interval's own base + 1u */
jpl_bool jpl_frame_list_is_live(jpl_ref h);   /* h in the current interval and below next: after
   a swap a handle from the other interval reads dead WHILE SITTING BELOW
   next, which is the case §6.6's `h < next` could not distinguish and
   §6.7's aliasing debt named */
jpl_ref jpl_frame_list_word_at(jpl_ref h, jpl_ref i);   /* one WORD of jpl_frame_list_cell, in the struct's own
                                    field order: i is a position, not a byte, and an
                                    index past the cell answers JPL_NIL (§6.7 paragraph
                                    5bis).  The chain is derived from the members the
                                    layout rule that emitted jpl_frame_list_cell registered, so it cannot
                                    describe a cell other than the one frame_list_edge classes */
void jpl_frame_list_word_put(jpl_ref h, jpl_ref i, jpl_ref v);   /* the scan's one write, over the
                                    same arms as jpl_frame_list_word_at: no cell in this tree is
                                    written through an address */
jpl_ref jpl_frame_list_evac(jpl_ref h);   /* copy jpl_frame_list_cell's cell h into the current interval and
                                    return the copy, or forward to the copy already made
                                    (§6.7 paragraph 5bis: the four-arm test on frame_list_origin,
                                    one C99 structure assignment, and alloc clearing the
                                    origin of every cell it hands out) */
void jpl_frame_list_queue_start(void);   /* scan = CUR_BASE + 1u, the same expression
                                    reset uses, after evac has copied the
                                    roots that make the queue non-empty */
void jpl_frame_list_scan_one(void);   /* rewrite frame_list's EDGE words at scan and advance
                                    scan by one cell */
void jpl_frame_list_drain(void);   /* scan_one until scan reaches next: a fixpoint
                                    over frame_list's to region, bounded by the
                                    interval (R3) and not recursive (R4) */

/* §4.2 wants one observable place: the saturating sum of every pool's refusals.
   A lowering reads a nil handle as the same edge a fired branch_guardb is
   (§5), and the host reads this as the run's verdict. */
jpl_nat jpl_pools_refusals(void);

/* Which of the two intervals is current is ONE mutable global (§6.7 paragraph 4),
   declared beside the pools section that sizes them and written by ONE function.
   A second writer would be a second cause for a fact the graph agrees on, and
   the gate counts assignments to the global rather than trusting this sentence:
   it is the only name in this runtime whose value every pool's bounds read. */
jpl_nat jpl_pools_swap(void);   /* advance to the next interval; returns the new index,
                  so a caller can observe the flip without reading the
                  global it is the one writer of */
typedef char jpl_check_pools_flip_cycles_the_intervals[
   (((1u % JPL_POOL_SPACES) == 1u) && ((1u + 1u) % JPL_POOL_SPACES == 0u)) ? 1 : -1];   /* the flip
   is a TWO-interval cycle, which is exactly what each pool's _two_regions
   check sizes its array for: raise the headroom factor to three and this fails
   at compile time instead of leaving a third interval no bound ever selects */

/* The scan's word is a handle whose POOL the edge table says, not one the
   cell's own type says, so the dispatch over the class ids is ONE function
   for the whole runtime (§6.7 paragraph 5bis) rather than eight that would
   each need a second table to name the target.  unclassified is its
   refuse-and-count edge: the one global that says a class was read that no
   arm covers, which the gate measures against the target set the tables
   were built from.  A lowering owns the order — queue_start, evac the roots,
   drain — and this layer only supplies the parts. */
extern jpl_nat jpl_pools_unclassified;
jpl_ref jpl_pools_evac_by_class(jpl_nat cls, jpl_ref h);

/* ── the pool edge tables (JPL.md §6.7, 5-B.3b-ii-b-2a): what each WORD of a
   pool cell means, so a collector's reachability rule is read from a table
   the layout derived rather than invented by a body.  R7's slots are one
   uint32_t each and cannot tell a handle from a count; this is the second
   reading of the same declarations that says which is which — one class per
   word, because R3 keeps a list's element inline, so a pair cell's element
   is two words and no second table is needed to say how a field splits.  A
   by-value aggregate whose words mean something only under a tag (an option,
   a fat variant) has NO reading here: the emitter refuses one rather than
   guessing which words are live.  Declarations here, definitions in
   sh_run_jpl_pools.c with the runtime they serve, and every row width pinned
   against its cell's sizeof by the typedef under it. ── */
#define JPL_EDGE_SCALAR 0u   /* a value: nothing to forward */
#define JPL_EDGE_UNUSED 1u   /* past this row's arity: a word never written */
#define JPL_EDGE_TO_CMD_POOL 3u   /* target: jpl_cmd_pool */
#define JPL_EDGE_TO_CMD_LIST_POOL 4u   /* target: jpl_cmd_list_pool */
#define JPL_EDGE_TO_FRAME_POOL 5u   /* target: jpl_frame_pool */
#define JPL_EDGE_TO_FRAME_LIST_POOL 6u   /* target: jpl_frame_list_pool */
#define JPL_EDGE_TO_PAIR_TEXT_LIST_CMD_LIST_LIST_POOL 7u   /* target: jpl_pair_text_list_cmd_list_list_pool */
#define JPL_EDGE_TO_PAIR_TEXT_TEXT_LIST_POOL 8u   /* target: jpl_pair_text_text_list_pool */
#define JPL_EDGE_TO_TEXT_LIST_POOL 9u   /* target: jpl_text_list_pool */
#define JPL_EDGE_TO_WORD_POOL 10u   /* target: jpl_word_pool */
#define JPL_EDGE_POOL_COUNT 8u   /* targets an edge may name */

typedef char jpl_check_dispatch_arms_cover_every_target[
    ((JPL_EDGE_POOL_COUNT + 2u) == JPL_EDGE_TO_WORD_POOL) ? 1 : -1];   /* the target ids
     are handed out in the sorted-stem order above, starting one past the two fixed
     classes, so the highest id in the domain is COUNT + 2u and it belongs to word.  The
     dispatch in the pools TU has one arm per target, so this says the LAST arm it can
     reach is the LAST id a table can contain: an unreachable class would be a table
     word whose target no arm names, i.e. a live cell the scan leaves in the interval
     the boundary abandons.  Pinned here rather than in a sentence because the count,
     the order and the id base are three numbers only the emitter's own sort ties. */

/* word: 1 row x 257 words per jpl_text — the cell is a LEAF: every word is a value, so its scan copies it and follows nothing */
#define JPL_WORD_NPOS 257u    /* words per cell */
#define JPL_WORD_NROWS 1u   /* rows: 1, an untagged cell */
#define JPL_WORD_NEDGE (JPL_WORD_NROWS * JPL_WORD_NPOS)
extern const jpl_nat jpl_word_edge[JPL_WORD_NEDGE];
typedef char jpl_check_word_edge_covers_the_cell[((JPL_WORD_NPOS * 4u) == sizeof (jpl_text)) ? 1 : -1];

/* pair_text_text_list: 1 row x 3 words per jpl_pair_text_text_list_cell — a cons cell: the element inline in the cell, then the tail */
#define JPL_PAIR_TEXT_TEXT_LIST_NPOS 3u    /* words per cell */
#define JPL_PAIR_TEXT_TEXT_LIST_NROWS 1u   /* rows: 1, an untagged cell */
#define JPL_PAIR_TEXT_TEXT_LIST_NEDGE (JPL_PAIR_TEXT_TEXT_LIST_NROWS * JPL_PAIR_TEXT_TEXT_LIST_NPOS)
extern const jpl_nat jpl_pair_text_text_list_edge[JPL_PAIR_TEXT_TEXT_LIST_NEDGE];
typedef char jpl_check_pair_text_text_list_edge_covers_the_cell[((JPL_PAIR_TEXT_TEXT_LIST_NPOS * 4u) == sizeof (jpl_pair_text_text_list_cell)) ? 1 : -1];

/* cmd: 11 rows x 4 words per jpl_cmd_node — one row per constructor, in the artifact's declaration order */
#define JPL_CMD_NPOS 4u    /* words per cell */
#define JPL_CMD_NROWS 11u   /* rows: constructors */
#define JPL_CMD_NEDGE (JPL_CMD_NROWS * JPL_CMD_NPOS)
extern const jpl_nat jpl_cmd_edge[JPL_CMD_NEDGE];
typedef char jpl_check_cmd_edge_covers_the_cell[((JPL_CMD_NPOS * 4u) == sizeof (jpl_cmd_node)) ? 1 : -1];

/* text_list: 1 row x 2 words per jpl_text_list_cell — a cons cell: the element inline in the cell, then the tail */
#define JPL_TEXT_LIST_NPOS 2u    /* words per cell */
#define JPL_TEXT_LIST_NROWS 1u   /* rows: 1, an untagged cell */
#define JPL_TEXT_LIST_NEDGE (JPL_TEXT_LIST_NROWS * JPL_TEXT_LIST_NPOS)
extern const jpl_nat jpl_text_list_edge[JPL_TEXT_LIST_NEDGE];
typedef char jpl_check_text_list_edge_covers_the_cell[((JPL_TEXT_LIST_NPOS * 4u) == sizeof (jpl_text_list_cell)) ? 1 : -1];

/* cmd_list: 1 row x 2 words per jpl_cmd_list_cell — a cons cell: the element inline in the cell, then the tail */
#define JPL_CMD_LIST_NPOS 2u    /* words per cell */
#define JPL_CMD_LIST_NROWS 1u   /* rows: 1, an untagged cell */
#define JPL_CMD_LIST_NEDGE (JPL_CMD_LIST_NROWS * JPL_CMD_LIST_NPOS)
extern const jpl_nat jpl_cmd_list_edge[JPL_CMD_LIST_NEDGE];
typedef char jpl_check_cmd_list_edge_covers_the_cell[((JPL_CMD_LIST_NPOS * 4u) == sizeof (jpl_cmd_list_cell)) ? 1 : -1];

/* pair_text_list_cmd_list_list: 1 row x 3 words per jpl_pair_text_list_cmd_list_list_cell — a cons cell: the element inline in the cell, then the tail */
#define JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_NPOS 3u    /* words per cell */
#define JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_NROWS 1u   /* rows: 1, an untagged cell */
#define JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_NEDGE (JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_NROWS * JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_NPOS)
extern const jpl_nat jpl_pair_text_list_cmd_list_list_edge[JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_NEDGE];
typedef char jpl_check_pair_text_list_cmd_list_list_edge_covers_the_cell[((JPL_PAIR_TEXT_LIST_CMD_LIST_LIST_NPOS * 4u) == sizeof (jpl_pair_text_list_cmd_list_list_cell)) ? 1 : -1];

/* frame: 9 rows x 5 words per jpl_frame_node — one row per constructor, in the artifact's declaration order */
#define JPL_FRAME_NPOS 5u    /* words per cell */
#define JPL_FRAME_NROWS 9u   /* rows: constructors */
#define JPL_FRAME_NEDGE (JPL_FRAME_NROWS * JPL_FRAME_NPOS)
extern const jpl_nat jpl_frame_edge[JPL_FRAME_NEDGE];
typedef char jpl_check_frame_edge_covers_the_cell[((JPL_FRAME_NPOS * 4u) == sizeof (jpl_frame_node)) ? 1 : -1];

/* frame_list: 1 row x 2 words per jpl_frame_list_cell — a cons cell: the element inline in the cell, then the tail */
#define JPL_FRAME_LIST_NPOS 2u    /* words per cell */
#define JPL_FRAME_LIST_NROWS 1u   /* rows: 1, an untagged cell */
#define JPL_FRAME_LIST_NEDGE (JPL_FRAME_LIST_NROWS * JPL_FRAME_LIST_NPOS)
extern const jpl_nat jpl_frame_list_edge[JPL_FRAME_LIST_NEDGE];
typedef char jpl_check_frame_list_edge_covers_the_cell[((JPL_FRAME_LIST_NPOS * 4u) == sizeof (jpl_frame_list_cell)) ? 1 : -1];


/* ── prototypes for the shipped closure: parameter names are the artifact's
   own, and every type comes from the .mli signature mapped by the rule set. */
/* PENDING polymorphic length : 'a1 list -> int
   reached from 6 closure bindings; a C instance must be chosen per call
   site, so JPL.md §6's "no monomorphization" claim is refuted by this
   binding and the instance set belongs to JPL.5-B.3's call-site census. */
/* PENDING polymorphic app : 'a1 list -> 'a1 list -> 'a1 list
   reached from 2 closure bindings; a C instance must be chosen per call
   site, so JPL.md §6's "no monomorphization" claim is refuted by this
   binding and the instance set belongs to JPL.5-B.3's call-site census. */
jpl_nat jpl_add(jpl_nat a0, jpl_nat a1);
jpl_nat jpl_mul(jpl_nat a0, jpl_nat a1);
/* PENDING polymorphic rev : 'a1 list -> 'a1 list
   reached from 3 closure bindings; a C instance must be chosen per call
   site, so JPL.md §6's "no monomorphization" claim is refuted by this
   binding and the instance set belongs to JPL.5-B.3's call-site census. */
/* PENDING polymorphic rev_append : 'a1 list -> 'a1 list -> 'a1 list
   reached from 3 closure bindings; a C instance must be chosen per call
   site, so JPL.md §6's "no monomorphization" claim is refuted by this
   binding and the instance set belongs to JPL.5-B.3's call-site census. */
/* PENDING polymorphic forallb : ('a1 -> bool) -> 'a1 list -> bool
   reached from 2 closure bindings; a C instance must be chosen per call
   site, so JPL.md §6's "no monomorphization" claim is refuted by this
   binding and the instance set belongs to JPL.5-B.3's call-site census. */
jpl_bool jpl_teqb(jpl_wref s1, jpl_wref s2);
jpl_nat jpl_bstat(jpl_nat n);
jpl_opt_text jpl_getv(jpl_wref a0, jpl_pair_text_text_list a1);
#define JPL_C_B_DOLLAR 36u   /* b_dollar : int */
#define JPL_C_B_LBRACE 123u   /* b_lbrace : int */
#define JPL_C_B_RBRACE 125u   /* b_rbrace : int */
#define JPL_C_B_QMARK 63u   /* b_qmark : int */
#define JPL_C_B_USCORE 95u   /* b_uscore : int */
#define JPL_C_B_0 48u   /* b_0 : int */
jpl_bool jpl_is_digit(jpl_nat b);
jpl_bool jpl_is_alpha(jpl_nat b);
jpl_bool jpl_is_name(jpl_nat b);
jpl_wref jpl_nat_digits(jpl_nat f, jpl_nat n, jpl_wref acc);
jpl_wref jpl_nat2text(jpl_nat n);
#define JPL_C_B_STAR 42u   /* b_star : int */
/* mAX_WORD : int = 256 is already defined above as JPL_MAX_WORD — one number, one
   name, so the cap the C allocates against is the cap the artifact carries. */
/* mAX_LIST : int = 1024 is already defined above as JPL_MAX_LIST — one number, one
   name, so the cap the C allocates against is the cap the artifact carries. */
/* gLOB_FUEL : int = 132353 is already defined above as JPL_GLOB_FUEL — one number, one
   name, so the cap the C allocates against is the cap the artifact carries. */
/* mAX_FUEL : int = 136449 is already defined above as JPL_MAX_FUEL — one number, one
   name, so the cap the C allocates against is the cap the artifact carries. */
jpl_bword jpl_raw_bword(jpl_wref l);
jpl_bool jpl_isz(jpl_cstate s);
jpl_out jpl_enter_seq(jpl_nat h, jpl_cmd_list l, jpl_cstate s, jpl_frame_list k);
jpl_bool jpl_glob_it(jpl_nat f, jpl_wref pat, jpl_wref str, jpl_opt_pair_text_text bk);
jpl_bool jpl_glob_iter(jpl_nat f, jpl_wref pat, jpl_wref str);
jpl_bool jpl_match_any_iter(jpl_nat f, jpl_text_list pats, jpl_wref scrut);
jpl_nat jpl_branch_need(jpl_text_list pats, jpl_wref w);
jpl_bool jpl_branch_guardb(jpl_nat g, jpl_text_list pats, jpl_wref w);
jpl_opt_pair_text_text_list jpl_setv_it(jpl_nat f, jpl_wref k, jpl_wref v, jpl_pair_text_text_list acc, jpl_pair_text_text_list m);
jpl_wref jpl_ek_value(jpl_pair_text_text_list m, jpl_wref nm);
jpl_wref jpl_expand_go(jpl_nat f, jpl_pair_text_text_list m, jpl_nat st, jpl_exp_k k);
jpl_wref jpl_expand_it(jpl_nat f, jpl_pair_text_text_list m, jpl_nat st, jpl_wref inp);
jpl_bres_bword jpl_expand_c(jpl_nat f, jpl_pair_text_text_list m, jpl_nat st, jpl_wref inp);
jpl_out jpl_assign_c(jpl_wref nm, jpl_wref val0, jpl_frame_list k, jpl_cstate s);
jpl_opt_cstate jpl_bind_word_o(jpl_nat g, jpl_wref var, jpl_wref w, jpl_cstate s);
jpl_out jpl_enter_for_c(jpl_nat h, jpl_wref var, jpl_text_list ws, jpl_cmd_list body, jpl_cstate s, jpl_frame_list k);
jpl_out jpl_enter_case_c(jpl_nat h, jpl_wref scrut, jpl_pair_text_list_cmd_list_list brs, jpl_cstate s, jpl_frame_list k);
jpl_out jpl_step_cmd_c(jpl_nat f, jpl_cmd c, jpl_frame_list k, jpl_cstate s);
jpl_out jpl_step_ret_c(jpl_frame_list k, jpl_cstate s);
jpl_out jpl_step_c(jpl_cfg g);
jpl_dres jpl_mrun_c(jpl_nat b, jpl_cfg g);

#endif /* SH_RUN_JPL_H */
