(* sh_extract_iter.v
 *
 * Drives the extraction of the ITERATIVE, JPL-shaped kernel (sh_jpl_run.v's
 * non-recursive `step` dispatcher and fuel-bounded tail driver `mloop`) down to
 * runnable OCaml — the derived half of the single-source pipeline for the
 * small-step machine (Phase 3d-C / JPL.4).  Nothing here is proof-bearing; it
 * only configures and invokes the Extraction machinery.
 *
 * It ALSO extracts the recursive reference `run` alongside the machine, into the
 * SAME module, so both share one set of extracted datatypes (nat/text/cmd/cstate).
 * That lets sh_run_iter_parity.ml evaluate `run` and `mloop` on identical inputs
 * and assert they agree — a behavioural isomorphism check between the reference
 * semantics and the JPL-shaped iterative kernel, with no type-coercion glue.
 *
 * sh_run_iter.ml / sh_run_iter.mli are BUILD ARTIFACTS: regenerated by
 * verify_models.sh and removed on cleanup.  They are never edited by hand, so
 * sh_concrete.v / sh_jpl_run.v stay the single sources of truth.  This is a
 * SECOND, additive artifact; it does not touch sh_run.ml (the vendored recursive
 * kernel ush links against), so that gate stays green.
 *
 * Build:
 *   coqc sh_concrete.v; coqc sh_jpl.v; coqc sh_jpl_run.v
 *   coqc sh_extract_iter.v     # writes sh_run_iter.ml + sh_run_iter.mli
 *)
From Stdlib Require Import Extraction.
From Stdlib Require Import ExtrOcamlBasic.
Require Import sh_concrete.
Require Import sh_jpl.
Require Import sh_jpl_run.   (* the machine: step/mloop + enter_* helpers *)

(* Emit beside this file so the gate's ocamlc finds them. *)
Set Extraction Output Directory ".".

(* list / option / bool / product map to their OCaml originals; nat is left as
   Peano (the fuel/step-budget guards match O vs S, which an int could not
   express).  We name the whole executable surface of the machine:
     - step / mloop : the JPL-shaped control kernel (non-recursive dispatch +
       tail driver) — the code the Phase-3d-C emitter will target;
     - run + helpers : the recursive reference, extracted into the SAME module so
       the parity harness can cross-check mloop against run on shared datatypes;
     - pure_phi / expand / glob : the verified leaf and the scan helpers the
       machine drives, exposed so §8's expander/globber checks run through the
       same extracted code path as the machine uses internally. *)
Extraction "sh_run_iter" step mloop run pure_phi expand glob.
