(* sh_extract.v
 *
 * Drives the extraction of the verified concrete model (sh_concrete.v) down to
 * runnable OCaml — the "derived" half of the single-source pipeline
 * Coq ==> OCaml ==> (Phase 3d) C99.  Nothing in this file is proof-bearing; it
 * only configures and invokes the Extraction machinery.
 *
 * sh_run.ml / sh_run.mli are BUILD ARTIFACTS: regenerated by verify_models.sh
 * and removed on cleanup.  They are never edited by hand, so sh_concrete.v stays
 * the single source of truth (no model doubling).
 *
 * Build:
 *   coqc sh_concrete.v      # produces sh_concrete.vo
 *   coqc sh_extract.v       # writes sh_run.ml + sh_run.mli
 *)
From Stdlib Require Import Extraction.
From Stdlib Require Import ExtrOcamlBasic.
Require Import sh_concrete.

(* Emit beside this file (the models dir) so the gate's ocamlc finds them; set
   explicitly to avoid the default-directory warning on manual runs. *)
Set Extraction Output Directory ".".

(* list / option / bool / product are mapped to their OCaml originals (via
   ExtrOcamlBasic) so the extracted program is idiomatic.  nat is deliberately
   LEFT as Peano: run and the expander bound their recursion by matching the
   fuel budget as `f = 0` vs `f = S f'`, which an int representation could not
   express, so the guard-checker's own recursion discipline survives extraction. *)

(* Recursively extract the executable surface.  `run` drags in its mutual
   helpers (run_seq / run_for / run_case) and, through them, the expander and the
   globber; expand and glob are named explicitly so the fidelity harness can also
   call them directly rather than only through run. *)
Extraction "sh_run" run expand glob.
